ALTER TABLE USER MODIFY COLUMN 	USERNAME VARCHAR(64) NOT NULL COMMENT 'Username';
ALTER TABLE USER MODIFY COLUMN 	EMAIL VARCHAR(128) NULL COMMENT 'Email';
ALTER TABLE USER MODIFY COLUMN 	PASSWORD VARCHAR(16) NULL COMMENT 'Password';
ALTER TABLE USER MODIFY COLUMN 	ROLE VARCHAR(16) NULL COMMENT 'ROLE';
ALTER TABLE USER MODIFY COLUMN 	FIRSTNAME VARCHAR(64) NULL COMMENT 'Firstname';
ALTER TABLE USER MODIFY COLUMN 	LASTNAME VARCHAR(64) NULL COMMENT 'Lastname';


ALTER TABLE CONFIG MODIFY COLUMN	NAME VARCHAR(64) NOT NULL COMMENT 'Name';
ALTER TABLE CONFIG MODIFY COLUMN	VALUE VARCHAR(2048) NULL COMMENT 'Value';

ALTER TABLE NEWS MODIFY COLUMN	TITLE VARCHAR(200) NOT NULL COMMENT 'Title';
ALTER TABLE NEWS MODIFY COLUMN	CONTENT VARCHAR(2048) NULL COMMENT 'Content';
ALTER TABLE NEWS MODIFY COLUMN	NEWS_DATETIME DATETIME NULL COMMENT 'News Reported Time';
	

ALTER TABLE DC_MOTOR_CATEGORY MODIFY COLUMN	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category';
ALTER TABLE DC_MOTOR_CATEGORY MODIFY COLUMN	TYPE VARCHAR(32) NULL COMMENT 'Type';
ALTER TABLE DC_MOTOR_CATEGORY MODIFY COLUMN	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name';
ALTER TABLE DC_MOTOR_CATEGORY MODIFY COLUMN	DESCRIPTION VARCHAR(256) NULL COMMENT 'Description';
ALTER TABLE DC_MOTOR_CATEGORY MODIFY COLUMN	TECHNICAL_DATA VARCHAR(256) NULL COMMENT 'Technical Data';
	

ALTER TABLE DC_MOTOR_SERIES MODIFY COLUMN	SERIES VARCHAR(32) NOT NULL COMMENT 'Series';
ALTER TABLE DC_MOTOR_SERIES MODIFY COLUMN	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category';
ALTER TABLE DC_MOTOR_SERIES MODIFY COLUMN	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name';
ALTER TABLE DC_MOTOR_SERIES MODIFY COLUMN	DESCRIPTION VARCHAR(500) NULL COMMENT 'Description';
ALTER TABLE DC_MOTOR_SERIES MODIFY COLUMN	TECHNICAL_DATA VARCHAR(256) NULL COMMENT 'Technical Data';
	

ALTER TABLE DC_MOTOR MODIFY COLUMN	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category';
ALTER TABLE DC_MOTOR MODIFY COLUMN	SERIES VARCHAR(32) NULL COMMENT 'Series';
ALTER TABLE DC_MOTOR MODIFY COLUMN	MODEL VARCHAR(64) NOT NULL COMMENT 'Model';
ALTER TABLE DC_MOTOR MODIFY COLUMN	NAME VARCHAR(64) NOT NULL COMMENT 'Name';
ALTER TABLE DC_MOTOR MODIFY COLUMN	DESCRIPTION VARCHAR(256) NULL COMMENT 'Description';
	
ALTER TABLE DC_MOTOR MODIFY COLUMN	FRAME_SIZE DECIMAL(10, 2) NULL COMMENT 'Frame Size';
ALTER TABLE DC_MOTOR MODIFY COLUMN	FRAME_SIZE_UNIT VARCHAR(16) NULL COMMENT 'Frame Size Unit';
ALTER TABLE DC_MOTOR MODIFY COLUMN	FRAME_SIZE_TYPE VARCHAR(16) NULL COMMENT 'Frame Size Type';			-- DIAMETER (φ), SIDE (□)
ALTER TABLE DC_MOTOR MODIFY COLUMN	NEMA_SIZE DECIMAL(8, 0) NULL COMMENT 'NEMA';
	
ALTER TABLE DC_MOTOR MODIFY COLUMN	LENGTH DECIMAL(10, 2) NULL COMMENT 'Motor Length';
ALTER TABLE DC_MOTOR MODIFY COLUMN	LENGTH_UNIT VARCHAR(16) NULL COMMENT 'Motor Length Unit';				-- mm, cm
	
ALTER TABLE DC_MOTOR MODIFY COLUMN	WEIGHT DECIMAL(10, 2) NULL COMMENT 'Motor Weight';
ALTER TABLE DC_MOTOR MODIFY COLUMN	WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Motor Weight Unit';				-- g

ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_VOLTAGE DECIMAL(10, 2) NULL COMMENT 'Rated Voltage';
ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_VOLTAGE_UNIT VARCHAR(16) NULL COMMENT 'Rated Voltage Unit';		-- V

ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_CURRENT DECIMAL(10, 4) NULL COMMENT 'Rated Current';
ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Rated Current Unit';		-- A

ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_POWER DECIMAL(10, 2) NULL COMMENT 'Rated Power';
ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_POWER_UNIT VARCHAR(16) NULL COMMENT 'Rated Power Unit';			-- W

ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_TORQUE DECIMAL(10, 4) NULL COMMENT 'Rated Torque';
ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Rated Torque Unit';			-- Nm
	
ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_ROTATING_SPEED INT UNSIGNED NULL COMMENT 'Rated Speed';
ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_ROTATING_SPEED_UNIT VARCHAR(16) NULL COMMENT 'Rated Speed Unit';	-- rpm
	
ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_LINEAR_SPEED DECIMAL(10, 2) NULL COMMENT 'Rated Linear Speed';
ALTER TABLE DC_MOTOR MODIFY COLUMN	RATED_LINEAR_SPEED_UNIT VARCHAR(16) NULL COMMENT 'Rated Linear Speed Unit';	-- mps

ALTER TABLE DC_MOTOR MODIFY COLUMN	PEAK_CURRENT DECIMAL(10, 4) NULL COMMENT 'Peak Current';
ALTER TABLE DC_MOTOR MODIFY COLUMN	PEAK_CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Peak Current Unit';			-- A

ALTER TABLE DC_MOTOR MODIFY COLUMN	PEAK_TORQUE DECIMAL(10, 4) NULL COMMENT 'Peak Torque';
ALTER TABLE DC_MOTOR MODIFY COLUMN	PEAK_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Peak Torque Unit';			-- Nm

ALTER TABLE DC_MOTOR MODIFY COLUMN	MAX_SORTING_WEIGHT DECIMAL(10, 2) NULL COMMENT 'Max Sorting Weight';
ALTER TABLE DC_MOTOR MODIFY COLUMN	MAX_SORTING_WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Max Sorting Weight Unit';	-- kg

ALTER TABLE DC_MOTOR MODIFY COLUMN	NOLOAD_CURRENT DECIMAL(10, 4) NULL COMMENT 'Noload Current';
ALTER TABLE DC_MOTOR MODIFY COLUMN	NOLOAD_CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Noload Current Unit';		-- mA

ALTER TABLE DC_MOTOR MODIFY COLUMN	NOLOAD_ROTATING_SPEED INT UNSIGNED NULL COMMENT 'Noload Speed';
ALTER TABLE DC_MOTOR MODIFY COLUMN	NOLOAD_ROTATING_SPEED_UNIT VARCHAR(16) NULL COMMENT 'Noload Speed Unit';	-- rpm


ALTER TABLE DC_MOTOR_SPEC MODIFY COLUMN	NAME VARCHAR(64) NOT NULL COMMENT 'Name';
ALTER TABLE DC_MOTOR_SPEC MODIFY COLUMN	UNIT VARCHAR(16) NULL COMMENT 'Unit';
ALTER TABLE DC_MOTOR_SPEC MODIFY COLUMN	VALUE VARCHAR(64) NULL COMMENT 'Value';


ALTER TABLE DC_MOTOR_PERF_MEASUREMENT MODIFY COLUMN	TITLE VARCHAR(64) NULL COMMENT 'Title';
ALTER TABLE DC_MOTOR_PERF_MEASUREMENT MODIFY COLUMN	VARIABLES VARCHAR(128) NULL COMMENT 'Variables';
ALTER TABLE DC_MOTOR_PERF_MEASUREMENT MODIFY COLUMN	`VALUES` VARCHAR(2048) NULL COMMENT 'Values';
ALTER TABLE DC_MOTOR_PERF_MEASUREMENT MODIFY COLUMN	CONDITIONS VARCHAR(64) NULL COMMENT 'Conditions';


ALTER TABLE MOTOR_CONFIG MODIFY COLUMN	MODEL_REFS VARCHAR(512) NOT NULL COMMENT 'Model Refs';
ALTER TABLE MOTOR_CONFIG MODIFY COLUMN	CONFIG_NAME VARCHAR(64) NOT NULL COMMENT 'Config Name';
ALTER TABLE MOTOR_CONFIG MODIFY COLUMN	CONFIG_VALUE VARCHAR(512) NULL COMMENT 'Config Value';


ALTER TABLE STEPPER_MOTOR_CATEGORY MODIFY COLUMN	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category';
ALTER TABLE STEPPER_MOTOR_CATEGORY MODIFY COLUMN	TYPE VARCHAR(32) NULL COMMENT 'Type';
ALTER TABLE STEPPER_MOTOR_CATEGORY MODIFY COLUMN	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name';
ALTER TABLE STEPPER_MOTOR_CATEGORY MODIFY COLUMN	DESCRIPTION VARCHAR(256) NULL COMMENT 'Description';
ALTER TABLE STEPPER_MOTOR_CATEGORY MODIFY COLUMN	TECHNICAL_DATA VARCHAR(256) NULL COMMENT 'Technical Data';
	

ALTER TABLE STEPPER_MOTOR_SERIES MODIFY COLUMN	SERIES VARCHAR(32) NOT NULL COMMENT 'Series';
ALTER TABLE STEPPER_MOTOR_SERIES MODIFY COLUMN	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category';
ALTER TABLE STEPPER_MOTOR_SERIES MODIFY COLUMN	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name';
ALTER TABLE STEPPER_MOTOR_SERIES MODIFY COLUMN	DESCRIPTION VARCHAR(500) NULL COMMENT 'Description';
ALTER TABLE STEPPER_MOTOR_SERIES MODIFY COLUMN	TECHNICAL_DATA VARCHAR(256) NULL COMMENT 'Technical Data';


ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category';			-- STEPPER_STANDARD, STEPPER_FLAT, STEPPER_WITH_CONTROL
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	SERIES VARCHAR(32) NULL COMMENT 'Series';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	MODEL VARCHAR(64) NOT NULL COMMENT 'Model';					-- In case of STEPPER_LINEAR, it represents MODEL instead 
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	NAME VARCHAR(64) NOT NULL COMMENT 'Name';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	DESCRIPTION VARCHAR(256) NULL COMMENT 'Description';
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	FRAME_SIZE DECIMAL(10, 2) NULL COMMENT 'Frame Size';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	FRAME_SIZE_UNIT VARCHAR(16) NULL COMMENT 'Frame Size Unit';			-- mm, cm
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	FRAME_SIZE_TYPE VARCHAR(16) NULL COMMENT 'Frame Size Type';			-- DIAMETER (φ), SIDE (□)
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	NEMA_SIZE DECIMAL(8, 0) NULL COMMENT 'NEMA';
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	LENGTH DECIMAL(10, 2) NULL COMMENT 'Motor Length';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	LENGTH_UNIT VARCHAR(16) NULL COMMENT 'Motor Length Unit';				-- mm, cm
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	WEIGHT DECIMAL(10, 2) NULL COMMENT 'Motor Weight';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Motor Weight Unit';				-- g
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	RATED_VOLTAGE DECIMAL(10, 2) NULL COMMENT 'Rated Voltage';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	RATED_VOLTAGE_UNIT VARCHAR(16) NULL COMMENT 'Rated Voltage Unit';		-- V
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	PHASE_CURRENT DECIMAL(10, 4) NULL COMMENT 'Phase Current';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	PHASE_CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Phase Current Unit';		-- A
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	PHASE_RESISTANCE DECIMAL(10, 2) NULL COMMENT 'Phase Resistance';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	PHASE_RESISTANCE_UNIT VARCHAR(16) NULL COMMENT 'Phase Resistance Unit';		-- ohm (Ω)
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	PHASE_INDUCTANCE DECIMAL(10, 2) NULL COMMENT 'Phase Inductance';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	PHASE_INDUCTANCE_UNIT VARCHAR(16) NULL COMMENT 'Phase Inductance Unit';		-- mH
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	HOLDING_TORQUE DECIMAL(10, 4) NULL COMMENT 'Holding Torque';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	HOLDING_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Holding Torque Unit';		-- Nm, Ncm
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	DETENT_TORQUE DECIMAL(10, 4) NULL COMMENT 'Detent Torque';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	DETENT_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Detent Torque Unit';		-- Nm, Ncm
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	STEP_ANGLE DECIMAL(10, 2) NULL COMMENT 'Step Angle';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	STEP_ANGLE_UNIT VARCHAR(16) NULL COMMENT 'Step Angle Unit';			-- DEG (°)
	
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	MAX_THRUST DECIMAL(10, 2) NULL COMMENT 'Max Thrust';
ALTER TABLE STEPPER_MOTOR MODIFY COLUMN	MAX_THRUST_UNIT VARCHAR(16) NULL COMMENT 'Max Thrust Unit';			-- N
	

ALTER TABLE STEPPER_MOTOR_SPEC MODIFY COLUMN	NAME VARCHAR(64) NOT NULL COMMENT 'Name';
ALTER TABLE STEPPER_MOTOR_SPEC MODIFY COLUMN	UNIT VARCHAR(16) NULL COMMENT 'Unit';
ALTER TABLE STEPPER_MOTOR_SPEC MODIFY COLUMN	VALUE VARCHAR(64) NULL COMMENT 'Value';


ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT MODIFY COLUMN	TITLE VARCHAR(64) NULL COMMENT 'Title';
ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT MODIFY COLUMN	VARIABLES VARCHAR(256) NULL COMMENT 'Variables';
ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT MODIFY COLUMN	CONDITIONS VARCHAR(64) NULL COMMENT 'Conditions';
ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT MODIFY COLUMN	`VALUES` VARCHAR(2048) NULL COMMENT 'Values';


ALTER TABLE LEAD_DEF MODIFY COLUMN	CODE VARCHAR(16) NOT NULL COMMENT 'Code';
ALTER TABLE LEAD_DEF MODIFY COLUMN	SCREW_DIAMETER_INCH DECIMAL(8, 4) NOT NULL COMMENT 'Screw Diameter (inch)';
ALTER TABLE LEAD_DEF MODIFY COLUMN	SCREW_DIAMETER_MM DECIMAL(8, 4) NOT NULL COMMENT 'Screw Diameter (mm)';
ALTER TABLE LEAD_DEF MODIFY COLUMN	LEAD_INCH DECIMAL(8, 4) NOT NULL COMMENT 'Lead (inch)';
ALTER TABLE LEAD_DEF MODIFY COLUMN	LEAD_MM DECIMAL(8, 4) NOT NULL COMMENT 'Lead (mm)';
ALTER TABLE LEAD_DEF MODIFY COLUMN	THREADS INT UNSIGNED NOT NULL COMMENT 'Threads';


ALTER TABLE GEARBOX_SERIES MODIFY COLUMN	SERIES VARCHAR(32) NOT NULL COMMENT 'Series';
ALTER TABLE GEARBOX_SERIES MODIFY COLUMN	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name';
ALTER TABLE GEARBOX_SERIES MODIFY COLUMN	DESCRIPTION VARCHAR(256) NULL COMMENT 'Description';
ALTER TABLE GEARBOX_SERIES MODIFY COLUMN	TECHNICAL_DATA VARCHAR(256) NULL COMMENT 'Techinical Data';


ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	SERIES VARCHAR(32) NULL COMMENT 'Series';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MODEL VARCHAR(64) NOT NULL COMMENT 'Model';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	NAME VARCHAR(64) NOT NULL COMMENT 'Name';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	DESCRIPTION VARCHAR(256) NULL COMMENT 'Description';

ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	FRAME_SIZE DECIMAL(10, 2) NULL COMMENT 'Frame Size';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	FRAME_SIZE_UNIT VARCHAR(16) NULL COMMENT 'Frame Size Unit';			-- mm, cm
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	FRAME_SIZE_TYPE VARCHAR(16) NULL COMMENT 'Frame Size Type';			-- DIAMETER (φ), SIDE (□)
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	NEMA_SIZE DECIMAL(8, 0) NULL COMMENT 'NEMA';
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	LENGTH DECIMAL(10, 2) NULL COMMENT 'Length';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	LENGTH_UNIT VARCHAR(16) NULL COMMENT 'Length Unit';				-- mm, cm
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	WEIGHT DECIMAL(10, 2) NULL COMMENT 'Weight';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Weight Unit';				-- g

ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	NUM_OF_STAGES INT NOT NULL COMMENT 'Number of Stages';
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	REDUCTION_RATIOS VARCHAR(64) NULL COMMENT 'Reduction Ratios';
		
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	EFFICIENCY DECIMAL(10, 2) NULL COMMENT 'Efficency';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	EFFICIENCY_UNIT VARCHAR(16) NULL COMMENT 'Efficiency Unit';				-- PERCENT (%)

ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	RATED_CONTINUOUS_TORQUE DECIMAL(10, 4) NULL COMMENT 'Rated Continuous Torque';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	RATED_CONTINUOUS_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Rated Continuous Torque Unit';	-- Nm
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_MOMENTARY_TORQUE DECIMAL(10, 4) NULL COMMENT 'Max Momentary Torque';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_MOMENTARY_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Max Momentary Torque Unit';		-- Nm
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_RADIAL_LOAD DECIMAL(10, 2) NULL COMMENT 'Max Radial Load';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_RADIAL_LOAD_UNIT VARCHAR(16) NULL COMMENT 'Max Radial Load Unit';
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_AXIAL_LOAD DECIMAL(10, 2) NULL COMMENT 'Max Axial Load';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_AXIAL_LOAD_UNIT VARCHAR(16) NULL COMMENT 'Max Axial Load Unit';
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_SHAFT_PRESS DECIMAL(10, 2) NULL COMMENT 'Max Shaft Press';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_SHAFT_PRESS_UNIT VARCHAR(16) NULL COMMENT 'Max Shaft Press Unit';
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_BACKLASH_NOLOAD DECIMAL(10, 2) NULL COMMENT 'Max Backlash Noload';
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	MAX_BACKLASH_NOLOAD_UNIT VARCHAR(16) NULL COMMENT 'Max Backlash Noload Unit';
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	OPERATING_TEMPERATURE VARCHAR(32) NULL COMMENT 'Operating Temperature';
	
ALTER TABLE PLANETARY_GEARBOX MODIFY COLUMN	RECOMMEND_INPUT_SPEED VARCHAR(32) NULL COMMENT 'Recommended Input Speed';
	

ALTER TABLE BRAKE_SERIES MODIFY COLUMN	SERIES VARCHAR(32) NOT NULL COMMENT 'Series';
ALTER TABLE BRAKE_SERIES MODIFY COLUMN	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name';
ALTER TABLE BRAKE_SERIES MODIFY COLUMN	DESCRIPTION VARCHAR(256) NULL COMMENT 'Description';
ALTER TABLE BRAKE_SERIES MODIFY COLUMN	TECHNICAL_DATA VARCHAR(256) NULL COMMENT 'Technical Data';


ALTER TABLE BRAKE MODIFY COLUMN	SERIES VARCHAR(32) NULL COMMENT 'Series';
ALTER TABLE BRAKE MODIFY COLUMN	MODEL VARCHAR(64) NOT NULL COMMENT 'Model';
ALTER TABLE BRAKE MODIFY COLUMN	NAME VARCHAR(64) NOT NULL COMMENT 'Name';
ALTER TABLE BRAKE MODIFY COLUMN	DESCRIPTION VARCHAR(256) NULL COMMENT 'Description';

ALTER TABLE BRAKE MODIFY COLUMN	FRAME_SIZE DECIMAL(10, 2) NULL COMMENT 'Frame Size';
ALTER TABLE BRAKE MODIFY COLUMN	FRAME_SIZE_UNIT VARCHAR(16) NULL COMMENT 'Frame Size Unit';			-- mm, cm
ALTER TABLE BRAKE MODIFY COLUMN	FRAME_SIZE_TYPE VARCHAR(16) NULL COMMENT 'Frame Size Type';			-- DIAMETER (φ), SIDE (□)
ALTER TABLE BRAKE MODIFY COLUMN	NEMA_SIZE DECIMAL(8, 0) NULL COMMENT 'NEMA';
		
ALTER TABLE BRAKE MODIFY COLUMN	LENGTH DECIMAL(10, 2) COMMENT 'Length';
ALTER TABLE BRAKE MODIFY COLUMN	LENGTH_UNIT VARCHAR(16) COMMENT 'Length Unit';					-- mm, cm
	
ALTER TABLE BRAKE MODIFY COLUMN	WEIGHT DECIMAL(10, 2) NULL COMMENT 'Weight';
ALTER TABLE BRAKE MODIFY COLUMN	WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Weight Unit';				-- g
	
ALTER TABLE BRAKE MODIFY COLUMN	RATED_VOLTAGE DECIMAL(10, 2) NULL COMMENT 'Rated Voltage';
ALTER TABLE BRAKE MODIFY COLUMN	RATED_VOLTAGE_UNIT VARCHAR(16) NULL COMMENT 'Rated Voltage Unit';		-- V
	
ALTER TABLE BRAKE MODIFY COLUMN	RESISTANCE DECIMAL(10, 2) NULL COMMENT 'Resistance';
ALTER TABLE BRAKE MODIFY COLUMN	RESISTANCE_UNIT VARCHAR(16) NULL COMMENT 'Resistance Unit';			-- ohm (Ω)
	
ALTER TABLE BRAKE MODIFY COLUMN	CURRENT DECIMAL(10, 4) NULL COMMENT 'Current';
ALTER TABLE BRAKE MODIFY COLUMN	CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Current Unit';				-- A

ALTER TABLE BRAKE MODIFY COLUMN	STATIC_TORQUE DECIMAL(10, 4) NULL COMMENT 'Static Torque';
ALTER TABLE BRAKE MODIFY COLUMN	STATIC_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Static Torque Unit';		-- Nm
	
ALTER TABLE BRAKE MODIFY COLUMN	RATED_POWER DECIMAL(10, 2) NULL COMMENT 'Rated Power';
ALTER TABLE BRAKE MODIFY COLUMN	RATED_POWER_UNIT VARCHAR(16) NULL COMMENT 'Rated Power Unit';			-- W
	
ALTER TABLE BRAKE MODIFY COLUMN	START_VOLTAGE DECIMAL(10, 2) COMMENT 'Start Voltage';
ALTER TABLE BRAKE MODIFY COLUMN	START_VOLTAGE_UNIT VARCHAR(16) COMMENT 'Start Voltage Unit';				-- V
	


ALTER TABLE INQUIRY MODIFY COLUMN	CONTACT_NAME VARCHAR(64) NULL COMMENT 'Contact Name';
ALTER TABLE INQUIRY MODIFY COLUMN	CONTACT_EMAIL VARCHAR(64) NULL COMMENT 'Contact Email';
ALTER TABLE INQUIRY MODIFY COLUMN	CONTACT_PHONE VARCHAR(64) NULL COMMENT 'Contact Phone';
ALTER TABLE INQUIRY MODIFY COLUMN	REF_MODEL VARCHAR(64) NULL COMMENT 'Ref Model';
ALTER TABLE INQUIRY MODIFY COLUMN	QUANTITY INT UNSIGNED NULL COMMENT 'Quantity';
ALTER TABLE INQUIRY MODIFY COLUMN	CONTENT VARCHAR(1024) NULL COMMENT 'Content';
ALTER TABLE INQUIRY MODIFY COLUMN	REF_LINK VARCHAR(256) NULL COMMENT 'Ref Link';
ALTER TABLE INQUIRY MODIFY COLUMN	CLIENT_IP_ADDRESS VARCHAR(64) NULL COMMENT 'Client IP Address';
ALTER TABLE INQUIRY MODIFY COLUMN	CLIENT_COUNTRY_OR_REGION VARCHAR(64) NULL COMMENT 'Client Country or Region';
ALTER TABLE INQUIRY MODIFY COLUMN	STATUS VARCHAR(32) NULL COMMENT 'Status';
