ALTER TABLE DC_MOTOR_PERF_MEASUREMENT ADD SAFE_THRESHOLD VARCHAR(64) NULL COMMENT 'Safe Threshold';

ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT ADD COLUMN SAFE_THRESHOLD VARCHAR(64) NULL COMMENT 'Safe Threshold';
