ALTER TABLE DC_MOTOR_PERF_MEASUREMENT ADD SAFE_THRESHOLD VARCHAR(64) NULL COMMENT 'Safe Threshold';

ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT ADD COLUMN SAFE_THRESHOLD VARCHAR(64) NULL COMMENT 'Safe Threshold';

CREATE TABLE DOWNLOAD_TRACKING (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

	DOWNLOAD_LINK VARCHAR(256) NULL COMMENT 'Download Link',
	CONTACT_EMAIL VARCHAR(64) NULL COMMENT 'Contact Email',
	CONTACT_NAME VARCHAR(64) NULL COMMENT 'Contact Name',
	CONTACT_PHONE VARCHAR(64) NULL COMMENT 'Contact Phone',
	COMPANY VARCHAR(64) NULL COMMENT 'Company',
	
	CONSTRAINT PK_DL_TRACKING_ID PRIMARY KEY (ID),
	
	INDEX IX_DL_TRACKING_DOWNLOAD_LINK (DOWNLOAD_LINK),
	INDEX IX_DL_TRACKING_CONTACT_EMAIL (CONTACT_EMAIL)
);
