ALTER TABLE DC_MOTOR_PERF_MEASUREMENT DROP COLUMN VARIABLES;
ALTER TABLE DC_MOTOR_PERF_MEASUREMENT DROP COLUMN `VALUES`;

ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT DROP COLUMN VARIABLES;
ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT DROP COLUMN `VALUES`;