ALTER TABLE DC_MOTOR_PERF_MEASUREMENT ADD COLUMN VALUES_TABLE VARCHAR(2048) NULL COMMENT 'Values Table';
UPDATE DC_MOTOR_PERF_MEASUREMENT SET VALUES_TABLE = CONCAT(VARIABLES, CHAR(10), `VALUES`);

ALTER TABLE STEPPER_MOTOR_PERF_MEASUREMENT ADD COLUMN VALUES_TABLE VARCHAR(2048) NULL COMMENT 'Values Table';
UPDATE STEPPER_MOTOR_PERF_MEASUREMENT SET VALUES_TABLE = CONCAT(VARIABLES, CHAR(10), `VALUES`);
