CREATE USER 'sa'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'sa';

GRANT ALL ON *.* TO 'sa'@'localhost' WITH GRANT OPTION;

CREATE DATABASE exmek;


-- grant all privileges on exmek.* to sa@'%' identified by 'sa';
-- grant all privileges on exmek.* to sa@localhost identified by 'sa';

CREATE TABLE CONFIG (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	NAME VARCHAR(64) NOT NULL,
	VALUE VARCHAR(2048) NULL,
	
	CONSTRAINT PK_CONFIG_ID PRIMARY KEY (ID),
	CONSTRAINT UK_NAME UNIQUE KEY (NAME)
);

CREATE TABLE NEWS (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	TITLE VARCHAR(200) NOT NULL,
	CONTENT VARCHAR(2048) NULL,
	
	NEWS_DATETIME DATETIME NULL,
	
	CONSTRAINT PK_NEWS_ID PRIMARY KEY (ID),
	CONSTRAINT UK_NEWS_TITLE UNIQUE KEY (TITLE),
	INDEX IX_NEWS_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_NEWS_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	INDEX IX_NEWS_DATETIME (NEWS_DATETIME)
);

CREATE TABLE MOTOR_CATEGORY (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CATEGORY VARCHAR(32) NOT NULL,
	DISPLAY_NAME VARCHAR(32) NULL,
	DESCRIPTION VARCHAR(256) NULL,
	TECHNICAL_DATA VARCHAR(256) NULL,
	
	CONSTRAINT PK_MOTOR_CATEGORY_ID PRIMARY KEY (ID),
	CONSTRAINT UK_MOTOR_CATEGORY_CATEGORY UNIQUE KEY (CATEGORY),
	INDEX IX_MOTOR_CATEGORY_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_MOTOR_CATEGORY_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);

CREATE TABLE MOTOR_SERIES (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CATEGORY VARCHAR(32) NOT NULL,
	SERIES VARCHAR(32) NOT NULL,
	DESCRIPTION VARCHAR(500) NULL,
	TECHNICAL_DATA VARCHAR(256) NULL,
	
	CONSTRAINT PK_MOTOR_SERIES_ID PRIMARY KEY (ID),
	CONSTRAINT UK_MOTOR_SERIES_SERIES UNIQUE KEY (SERIES),
	CONSTRAINT FK_MOTOR_SERIES_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES MOTOR_CATEGORY (CATEGORY),
	INDEX IX_MOTOR_SERIES_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_MOTOR_SERIES_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
	INDEX IX_MOTOR_SERIES_CATEGORY (CATEGORY)
);

CREATE TABLE DC_MOTOR (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

	CATEGORY VARCHAR(32) NOT NULL,					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	SERIES VARCHAR(32) NULL,
	MODEL VARCHAR(64) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(256) NULL,
	
	FRAME_SIZE DECIMAL(10, 2) NULL,
	FRAME_SIZE_UNIT VARCHAR(16) NULL,			-- mm, cm
	FRAME_SIZE_TYPE VARCHAR(16) NULL,			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE DECIMAL(8, 0) NULL,
	
	LENGTH DECIMAL(10, 2) NULL,
	LENGTH_UNIT VARCHAR(16) NULL,				-- mm, cm
	
	WEIGHT DECIMAL(10, 2) NULL,
	WEIGHT_UNIT VARCHAR(16) NULL,				-- g

	RATED_VOLTAGE DECIMAL(10, 2) NULL,
	RATED_VOLTAGE_UNIT VARCHAR(16) NULL,		-- V

	RATED_CURRENT DECIMAL(10, 4) NULL,
	RATED_CURRENT_UNIT VARCHAR(16) NULL,		-- A

	RATED_POWER DECIMAL(10, 2) NULL,
	RATED_POWER_UNIT VARCHAR(16) NULL,			-- W

	RATED_TORQUE DECIMAL(10, 4) NULL,
	RATED_TORQUE_UNIT VARCHAR(16) NULL,			-- Nm
	
	RATED_ROTATING_SPEED INT UNSIGNED NULL,
	RATED_ROTATING_SPEED_UNIT VARCHAR(16) NULL,	-- rpm
	
	RATED_LINEAR_SPEED DECIMAL(10, 2) NULL,
	RATED_LINEAR_SPEED_UNIT VARCHAR(16) NULL,	-- mps

	PEAK_CURRENT DECIMAL(10, 4) NULL,
	PEAK_CURRENT_UNIT VARCHAR(16) NULL,			-- A

	PEAK_TORQUE DECIMAL(10, 4) NULL,
	PEAK_TORQUE_UNIT VARCHAR(16) NULL,			-- Nm

	MAX_SORTING_WEIGHT DECIMAL(10, 2) NULL,
	MAX_SORTING_WEIGHT_UNIT VARCHAR(16) NULL,	-- kg

	NOLOAD_CURRENT DECIMAL(10, 4) NULL,
	NOLOAD_CURRENT_UNIT VARCHAR(16) NULL,		-- mA

	NOLOAD_ROTATING_SPEED INT UNSIGNED NULL,
	NOLOAD_ROTATING_SPEED_UNIT VARCHAR(16) NULL,-- rpm

	CONSTRAINT PK_DC_MOTOR_ID PRIMARY KEY (ID),
	CONSTRAINT UK_DC_MOTOR_MODEL UNIQUE KEY (MODEL),
	CONSTRAINT FK_DC_MOTOR_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES MOTOR_CATEGORY (CATEGORY),
	CONSTRAINT FK_DC_MOTOR_SERIES FOREIGN KEY (SERIES) REFERENCES MOTOR_SERIES (SERIES),
	INDEX IX_DC_MOTOR_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_DC_MOTOR_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
--	INDEX IX_DC_MOTOR_NAME (NAME),
	
	INDEX IX_DC_MOTOR_CATEGORY (CATEGORY),
	INDEX IX_DC_MOTOR_SERIES (SERIES),
	
	INDEX IX_DC_MOTOR_FRAME_SIZE (FRAME_SIZE),
	INDEX IX_DC_MOTOR_NEMA_SIZE (NEMA_SIZE),
	INDEX IX_DC_MOTOR_LENGTH (LENGTH),
	INDEX IX_DC_MOTOR_WEIGHT (WEIGHT),
	
	INDEX IX_DC_MOTOR_RATED_VOLTAGE (RATED_VOLTAGE),
	INDEX IX_DC_MOTOR_RATED_CURRENT (RATED_CURRENT),
	INDEX IX_DC_MOTOR_RATED_POWER (RATED_POWER),
	INDEX IX_DC_MOTOR_RATED_TORQUE (RATED_TORQUE),
	INDEX IX_DC_MOTOR_RATED_ROTATING_SPEED (RATED_ROTATING_SPEED),
	INDEX IX_DC_MOTOR_RATED_LINEAR_SPEED (RATED_LINEAR_SPEED),
	INDEX IX_DC_MOTOR_PEAK_CURRENT (PEAK_CURRENT),
	INDEX IX_DC_MOTOR_PEAK_TORQUE (PEAK_TORQUE),
	INDEX IX_DC_MOTOR_MAX_SORTING_WEIGHT (MAX_SORTING_WEIGHT)
);

CREATE TABLE DC_MOTOR_SPEC (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	UNIT VARCHAR(16) NULL,
	VALUE VARCHAR(64) NULL,

	CONSTRAINT PK_DC_MOTOR_SPEC_ID PRIMARY KEY (ID),
	CONSTRAINT FK_DC_MOTOR_SPEC_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES DC_MOTOR (ID),
	INDEX IX_DC_MOTOR_SPEC_NAME (NAME)
);

CREATE TABLE DC_MOTOR_PERF_MEASUREMENT (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	TITLE VARCHAR(64) NULL,
	VARIABLES VARCHAR(128) NULL,
	`VALUES` VARCHAR(2048) NULL,
	CONDITIONS VARCHAR(64) NULL,

	CONSTRAINT PK_DC_MOTOR_PERF_MEASUREMENT_ID PRIMARY KEY (ID),
	CONSTRAINT FK_DC_MOTOR_PERF_MEASUREMENT_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES DC_MOTOR (ID)
);

CREATE TABLE MOTOR_CONFIG (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	MODEL_REF VARCHAR(64) NOT NULL,
	
	CONFIG_NAME VARCHAR(32) NOT NULL,
	CONFIG_VALUE VARCHAR(256) NULL,
	
	CONSTRAINT PK_MOTOR_CONFIG_ID PRIMARY KEY (ID),
	INDEX IK_MOTOR_CONFIG_MODEL_REF (MODEL_REF)
);

CREATE TABLE STEPPER_MOTOR (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

	CATEGORY VARCHAR(32) NOT NULL,			-- STEPPER_STANDARD, STEPPER_FLAT, STEPPER_WITH_CONTROL
	SERIES VARCHAR(32) NULL,
	MODEL VARCHAR(64) NOT NULL,					-- In case of STEPPER_LINEAR, it represents MODEL instead 
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(256) NULL,
	
	FRAME_SIZE DECIMAL(10, 2) NULL,
	FRAME_SIZE_UNIT VARCHAR(16) NULL,			-- mm, cm
	FRAME_SIZE_TYPE VARCHAR(16) NULL,			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE DECIMAL(8, 0) NULL,
	
	LENGTH DECIMAL(10, 2) NULL,
	LENGTH_UNIT VARCHAR(16) NULL,				-- mm, cm
	
	WEIGHT DECIMAL(10, 2) NULL,
	WEIGHT_UNIT VARCHAR(16) NULL,				-- g
	
	RATED_VOLTAGE DECIMAL(10, 2) NULL,
	RATED_VOLTAGE_UNIT VARCHAR(16) NULL,		-- V
	
	PHASE_CURRENT DECIMAL(10, 4) NULL,
	PHASE_CURRENT_UNIT VARCHAR(16) NULL,		-- A
	
	PHASE_RESISTANCE DECIMAL(10, 2) NULL,
	PHASE_RESISTANCE_UNIT VARCHAR(16) NULL,		-- ohm (Ω)
	
	PHASE_INDUCTANCE DECIMAL(10, 2) NULL,
	PHASE_INDUCTANCE_UNIT VARCHAR(16) NULL,		-- mH
	
	HOLDING_TORQUE DECIMAL(10, 4) NULL,
	HOLDING_TORQUE_UNIT VARCHAR(16) NULL,		-- Nm, Ncm
	
	DETENT_TORQUE DECIMAL(10, 4) NULL,
	DETENT_TORQUE_UNIT VARCHAR(16) NULL,		-- Nm, Ncm
	
	STEP_ANGLE DECIMAL(10, 2) NULL,
	STEP_ANGLE_UNIT VARCHAR(16) NULL,			-- DEG (°)
	
	MAX_THRUST DECIMAL(10, 2) NULL,
	MAX_THRUST_UNIT VARCHAR(16) NULL,			-- N
	
	CONSTRAINT PK_STEPPER_MOTOR_ID PRIMARY KEY (ID),
	CONSTRAINT UK_STEPPER_MOTOR_MODEL UNIQUE KEY (MODEL),
	CONSTRAINT FK_STEPPER_MOTOR_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES MOTOR_CATEGORY (CATEGORY),
	CONSTRAINT FK_STEPPER_MOTOR_SERIES FOREIGN KEY (SERIES) REFERENCES MOTOR_SERIES (SERIES),
	INDEX IX_STEPPER_MOTOR_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_STEPPER_MOTOR_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
--	INDEX IX_STEPPER_MOTOR_NAME (NAME),
	
	INDEX IX_STEPPER_MOTOR_CATEGORY (CATEGORY),
	INDEX IX_STEPPER_MOTOR_SERIES (SERIES),
	
	INDEX IX_STEPPER_MOTOR_FRAME_SIZE (FRAME_SIZE),
	INDEX IX_STEPPER_MOTOR_NEMA_SIZE (NEMA_SIZE),
	INDEX IX_STEPPER_MOTOR_LENGTH (LENGTH),
	INDEX IX_STEPPER_MOTOR_WEIGHT (WEIGHT),
	
	INDEX IX_STEPPER_MOTOR_RATED_VOLTAGE (RATED_VOLTAGE),
	INDEX IX_STEPPER_MOTOR_PHASE_CURRENT (PHASE_CURRENT),
	INDEX IX_STEPPER_MOTOR_HOLDING_TORQUE (HOLDING_TORQUE),
	INDEX IX_STEPPER_MOTOR_DETENT_TORQUE (DETENT_TORQUE),
	INDEX IX_STEPPER_MOTOR_STEP_ANGLE (STEP_ANGLE),
	INDEX IX_STEPPER_MOTOR_MAX_THRUST (MAX_THRUST)
);

CREATE TABLE STEPPER_MOTOR_SPEC (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	UNIT VARCHAR(16) NULL,
	VALUE VARCHAR(64) NULL,

	CONSTRAINT PK_STEPPER_MOTOR_SPEC_ID PRIMARY KEY (ID),
	CONSTRAINT FK_STEPPER_MOTOR_SPEC_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES STEPPER_MOTOR (ID),
	INDEX IX_STEPPER_MOTOR_SPEC_NAME (NAME)
);

CREATE TABLE STEPPER_MOTOR_PERF_MEASUREMENT (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	TITLE VARCHAR(64) NULL,
	VARIABLES VARCHAR(256) NULL,
	CONDITIONS VARCHAR(64) NULL,
	`VALUES` VARCHAR(2048) NULL,

	CONSTRAINT PK_STEPPER_MOTOR_PERF_MEASUREMENT_ID PRIMARY KEY (ID),
	CONSTRAINT FK_STEPPER_MOTOR_PERF_MEASUREMENT_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES STEPPER_MOTOR (ID)
);

CREATE TABLE LEAD_DEF (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CODE VARCHAR(16) NOT NULL,
	SCREW_DIAMETER_INCH DECIMAL(8, 4) NOT NULL,
	SCREW_DIAMETER_MM DECIMAL(8, 4) NOT NULL,
	LEAD_INCH DECIMAL(8, 4) NOT NULL,
	LEAD_MM DECIMAL(8, 4) NOT NULL,
	THREADS INT UNSIGNED NOT NULL,
	
	CONSTRAINT PK_LEAD_DEF_ID PRIMARY KEY (ID),
	CONSTRAINT UK_LEAD_DEF_CODE UNIQUE KEY (CODE),
	INDEX IX_LEAD_DEF_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_LEAD_DEF_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);

CREATE TABLE LINEAR_STEPPER_MOTOR_LEAD (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	LEAD_ID INT UNSIGNED NOT NULL,

	CONSTRAINT PK_LS_MOTOR_LEAD_ID PRIMARY KEY (ID),
	CONSTRAINT FK_LS_MOTOR_LEAD_LEAD_ID FOREIGN KEY (LEAD_ID) REFERENCES LEAD_DEF (ID),
	CONSTRAINT FK_LS_MOTOR_LEAD_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES STEPPER_MOTOR (ID)
);

CREATE TABLE GEARBOX_SERIES (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NOT NULL,
	DESCRIPTION VARCHAR(256) NULL,
	TECHNICAL_DATA VARCHAR(256) NULL,
	
	CONSTRAINT PK_GEARBOX_SERIES_ID PRIMARY KEY (ID),
	CONSTRAINT UK_GEARBOX_SERIES_SERIES UNIQUE KEY (SERIES),
	INDEX IX_GEARBOX_SERIES_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_GEARBOX_SERIES_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);


CREATE TABLE PLANETARY_GEARBOX (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NULL,
	MODEL VARCHAR(64) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(256) NULL,

	FRAME_SIZE DECIMAL(10, 2) NULL,
	FRAME_SIZE_UNIT VARCHAR(16) NULL,			-- mm, cm
	FRAME_SIZE_TYPE VARCHAR(16) NULL,			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE DECIMAL(8, 0) NULL,
	
	LENGTH DECIMAL(10, 2) NULL,
	LENGTH_UNIT VARCHAR(16) NULL,				-- mm, cm
	
	WEIGHT DECIMAL(10, 2) NULL,
	WEIGHT_UNIT VARCHAR(16) NULL,				-- g

	NUM_OF_STAGES INT NOT NULL,
	
	REDUCTION_RATIOS VARCHAR(64) NULL,
		
	EFFICIENCY DECIMAL(10, 2) NULL,
	EFFICIENCY_UNIT VARCHAR(16) NULL,				-- PERCENT (%)

	RATED_CONTINUOUS_TORQUE DECIMAL(10, 4) NULL,
	RATED_CONTINUOUS_TORQUE_UNIT VARCHAR(16) NULL,	-- Nm
	
	MAX_MOMENTARY_TORQUE DECIMAL(10, 4) NULL,
	MAX_MOMENTARY_TORQUE_UNIT VARCHAR(16) NULL,		-- Nm
	
	MAX_RADIAL_LOAD DECIMAL(10, 2) NULL,
	MAX_RADIAL_LOAD_UNIT VARCHAR(16) NULL,
	
	MAX_AXIAL_LOAD DECIMAL(10, 2) NULL,
	MAX_AXIAL_LOAD_UNIT VARCHAR(16) NULL,
	
	MAX_SHAFT_PRESS DECIMAL(10, 2) NULL,
	MAX_SHAFT_PRESS_UNIT VARCHAR(16) NULL,
	
	MAX_BACKLASH_NOLOAD DECIMAL(10, 2) NULL,
	MAX_BACKLASH_NOLOAD_UNIT VARCHAR(16) NULL,
	
	OPERATING_TEMPERATURE VARCHAR(32) NULL,
	RECOMMEND_INPUT_SPEED VARCHAR(32) NULL,
	
	CONSTRAINT PK_PLANETARY_GEARBOX_ID PRIMARY KEY (ID),
	CONSTRAINT UK_PLANETARY_GEARBOX_MODEL UNIQUE KEY (MODEL),
	CONSTRAINT FK_PLANETARY_GEARBOX_SERIES FOREIGN KEY (SERIES) REFERENCES GEARBOX_SERIES (SERIES),
	INDEX IX_PLGB_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_PLGB_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
--	INDEX IX_PLGB_NAME (NAME),
	INDEX IX_PLGB_LENGTH (LENGTH),
	INDEX IX_PLGB_WEIGHT (WEIGHT),
	INDEX IX_PLGB_NUM_OF_STAGES (NUM_OF_STAGES),
	INDEX IX_PLGB_EFFICIENCY (EFFICIENCY),
	INDEX IX_PLGB_RATED_CONTINUOUS_TORQUE (RATED_CONTINUOUS_TORQUE),
	INDEX IX_PLGB_MAX_MOMENTARY_TORQUE (MAX_MOMENTARY_TORQUE)
);

CREATE TABLE BRAKE_SERIES (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NOT NULL,
	DESCRIPTION VARCHAR(256) NULL,
	TECHNICAL_DATA VARCHAR(256) NULL,
	
	CONSTRAINT PK_BRAKE_SERIES_ID PRIMARY KEY (ID),
	CONSTRAINT UK_BRAKE_SERIES_SERIES UNIQUE KEY (SERIES),
	INDEX IX_BRAKE_SERIES_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_BRAKE_SERIES_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);


CREATE TABLE BRAKE (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NULL,
	MODEL VARCHAR(64) NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(256) NULL,

	FRAME_SIZE DECIMAL(10, 2) NULL,
	FRAME_SIZE_UNIT VARCHAR(16) NULL,			-- mm, cm
	FRAME_SIZE_TYPE VARCHAR(16) NULL,			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE DECIMAL(8, 0) NULL,
		
	LENGTH DECIMAL(10, 2),
	LENGTH_UNIT VARCHAR(16),					-- mm, cm
	
	WEIGHT DECIMAL(10, 2) NULL,
	WEIGHT_UNIT VARCHAR(16) NULL,				-- g
	
	RATED_VOLTAGE DECIMAL(10, 2) NULL,
	RATED_VOLTAGE_UNIT VARCHAR(16) NULL,		-- V
	
	RESISTANCE DECIMAL(10, 2) NULL,
	RESISTANCE_UNIT VARCHAR(16) NULL,			-- ohm (Ω)
	
	CURRENT DECIMAL(10, 4) NULL,
	CURRENT_UNIT VARCHAR(16) NULL,				-- A

	STATIC_TORQUE DECIMAL(10, 4) NULL,
	STATIC_TORQUE_UNIT VARCHAR(16) NULL,		-- Nm
	
	RATED_POWER DECIMAL(10, 2) NULL,
	RATED_POWER_UNIT VARCHAR(16) NULL,			-- W
	
	START_VOLTAGE DECIMAL(10, 2),
	START_VOLTAGE_UNIT VARCHAR(16),				-- V
	

	CONSTRAINT PK_BRAKE_ID PRIMARY KEY (ID),
	CONSTRAINT UK_BRAKE_MODEL UNIQUE KEY (MODEL),
	CONSTRAINT FK_BRAKE_SERIES FOREIGN KEY (SERIES) REFERENCES BRAKE_SERIES (SERIES),
	INDEX IX_BRAKE_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_BRAKE_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
--	INDEX IX_BRAKE_NAME (NAME),
	INDEX IX_BRAKE_FRAME_SIZE (FRAME_SIZE),
	INDEX IX_BRAKE_NEMA_SIZE (NEMA_SIZE),
	INDEX IX_BRAKE_LENGTH (LENGTH),
	INDEX IX_BRAKE_WEIGHT (WEIGHT),
	INDEX IX_BRAKE_RATED_VOLTAGE (RATED_VOLTAGE),
	INDEX IX_BRAKE_RESISTANCE (RESISTANCE),
	INDEX IX_BRAKE_CURRENT (CURRENT),
	INDEX IX_BRAKE_STATIC_TORQUE (STATIC_TORQUE),
	INDEX IX_BRAKE_RATED_POWER (RATED_POWER),
	INDEX IX_BRAKE_START_VOLTAGE (START_VOLTAGE)
);

CREATE TABLE INQUIRY (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

	CONTACT_NAME VARCHAR(64) NULL,
	CONTACT_EMAIL VARCHAR(64) NULL,
	CONTACT_PHONE VARCHAR(64) NULL,
	REF_MODEL VARCHAR(64) NULL,
	QUANTITY INT UNSIGNED NULL,
	CONTENT VARCHAR(1024) NULL,
	REF_LINK VARCHAR(256) NULL,
	CLIENT_IP_ADDRRESS VARCHAR(64) NULL,
	CLIENT_HOST VARCHAR(64) NULL,
	CLIENT_COUNTRY VARCHAR(64) NULL,
	STATUS VARCHAR(32) NULL,
	
	CONSTRAINT PK_INQUIRY_ID PRIMARY KEY (ID),
	
	INDEX IX_INQUIRY_REF_MODEL (REF_MODEL)
);


