CREATE USER IF NOT EXISTS 'sa'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'sa';

GRANT ALL ON *.* TO 'sa'@'localhost' WITH GRANT OPTION;

CREATE DATABASE exmek;

-- grant all privileges on exmek.* to sa@'%' identified by 'sa';
-- grant all privileges on exmek.* to sa@localhost identified by 'sa';

USE exmek;

CREATE TABLE USER (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	USERNAME VARCHAR(64) NOT NULL COMMENT 'Username',
	EMAIL VARCHAR(128) NULL COMMENT 'Email',
	PASSWORD VARCHAR(16) NULL COMMENT 'Password',
	ROLE VARCHAR(16) NULL COMMENT 'ROLE',
	FIRSTNAME VARCHAR(64) NULL COMMENT 'Firstname',
	LASTNAME VARCHAR(64) NULL COMMENT 'Lastname',
	
	CONSTRAINT PK_USER_ID PRIMARY KEY (ID),
	CONSTRAINT UK_USERNAME UNIQUE KEY (USERNAME),
	CONSTRAINT UK_EMAIL UNIQUE KEY (EMAIL)
);


CREATE TABLE CONFIG (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	NAME VARCHAR(64) NOT NULL COMMENT 'Name',
	VALUE VARCHAR(2048) NULL COMMENT 'Value',
	
	CONSTRAINT PK_CONFIG_ID PRIMARY KEY (ID),
	CONSTRAINT UK_NAME UNIQUE KEY (NAME)
);

CREATE TABLE NEWS (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	TITLE VARCHAR(256) NOT NULL COMMENT 'Title',
	CONTENT VARCHAR(2048) NULL COMMENT 'Content',
	
	NEWS_DATETIME DATETIME NULL COMMENT 'News Reported Time',
	
	CONSTRAINT PK_NEWS_ID PRIMARY KEY (ID),
	CONSTRAINT UK_NEWS_TITLE UNIQUE KEY (TITLE),
	INDEX IX_NEWS_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_NEWS_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	INDEX IX_NEWS_DATETIME (NEWS_DATETIME)
);

CREATE TABLE DC_MOTOR_CATEGORY (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category',
	TYPE VARCHAR(32) NULL COMMENT 'Type',
	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name',
	DESCRIPTION VARCHAR(512) NULL COMMENT 'Description',
	TECHNICAL_DATA VARCHAR(512) NULL COMMENT 'Technical Data',
	
	CONSTRAINT PK_DC_MOTOR_CATEGORY_ID PRIMARY KEY (ID),
	CONSTRAINT UK_DC_MOTOR_CATEGORY_CATEGORY UNIQUE KEY (CATEGORY),
	INDEX IX_DC_MOTOR_CATEGORY_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_DC_MOTOR_CATEGORY_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);

CREATE TABLE DC_MOTOR_SERIES (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NOT NULL COMMENT 'Series',
	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category',
	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name',
	DESCRIPTION VARCHAR(512) NULL COMMENT 'Description',
	TECHNICAL_DATA VARCHAR(512) NULL COMMENT 'Technical Data',
	
	CONSTRAINT PK_DC_MOTOR_SERIES_ID PRIMARY KEY (ID),
	CONSTRAINT UK_DC_MOTOR_SERIES_SERIES UNIQUE KEY (SERIES),
	CONSTRAINT FK_DC_MOTOR_SERIES_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES DC_MOTOR_CATEGORY (CATEGORY),
	INDEX IX_DC_MOTOR_SERIES_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_DC_MOTOR_SERIES_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
	INDEX IX_DC_MOTOR_SERIES_CATEGORY (CATEGORY)
);

CREATE TABLE DC_MOTOR (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category',				-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	SERIES VARCHAR(32) NULL COMMENT 'Series',
	MODEL VARCHAR(64) NOT NULL COMMENT 'Model',
	NAME VARCHAR(64) NOT NULL COMMENT 'Name',
	DESCRIPTION VARCHAR(1024) NULL COMMENT 'Description',
	
	FRAME_SIZE DECIMAL(10, 2) NULL COMMENT 'Frame Size',
	FRAME_SIZE_UNIT VARCHAR(16) NULL COMMENT 'Frame Size Unit',			-- mm, cm
	FRAME_SIZE_TYPE VARCHAR(16) NULL COMMENT 'Frame Size Type',			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE DECIMAL(8, 0) NULL COMMENT 'NEMA',
	
	LENGTH DECIMAL(10, 2) NULL COMMENT 'Motor Length',
	LENGTH_UNIT VARCHAR(16) NULL COMMENT 'Motor Length Unit',				-- mm, cm
	
	WEIGHT DECIMAL(10, 2) NULL COMMENT 'Motor Weight',
	WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Motor Weight Unit',				-- g

	RATED_VOLTAGE DECIMAL(10, 2) NULL COMMENT 'Rated Voltage',
	RATED_VOLTAGE_UNIT VARCHAR(16) NULL COMMENT 'Rated Voltage Unit',		-- V

	RATED_CURRENT DECIMAL(10, 4) NULL COMMENT 'Rated Current',
	RATED_CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Rated Current Unit',		-- A

	RATED_POWER DECIMAL(10, 2) NULL COMMENT 'Rated Power',
	RATED_POWER_UNIT VARCHAR(16) NULL COMMENT 'Rated Power Unit',			-- W

	RATED_TORQUE DECIMAL(10, 4) NULL COMMENT 'Rated Torque',
	RATED_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Rated Torque Unit',			-- Nm
	
	RATED_ROTATING_SPEED INT UNSIGNED NULL COMMENT 'Rated Speed',
	RATED_ROTATING_SPEED_UNIT VARCHAR(16) NULL COMMENT 'Rated Speed Unit',	-- rpm
	
	RATED_LINEAR_SPEED DECIMAL(10, 2) NULL COMMENT 'Rated Linear Speed',
	RATED_LINEAR_SPEED_UNIT VARCHAR(16) NULL COMMENT 'Rated Linear Speed Unit',	-- mps

	PEAK_CURRENT DECIMAL(10, 4) NULL COMMENT 'Peak Current',
	PEAK_CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Peak Current Unit',			-- A

	PEAK_TORQUE DECIMAL(10, 4) NULL COMMENT 'Peak Torque',
	PEAK_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Peak Torque Unit',			-- Nm

	MAX_SORTING_WEIGHT DECIMAL(10, 2) NULL COMMENT 'Max Sorting Weight',
	MAX_SORTING_WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Max Sorting Weight Unit',	-- kg

	NOLOAD_CURRENT DECIMAL(10, 4) NULL COMMENT 'Noload Current',
	NOLOAD_CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Noload Current Unit',		-- mA

	NOLOAD_ROTATING_SPEED INT UNSIGNED NULL COMMENT 'Noload Speed',
	NOLOAD_ROTATING_SPEED_UNIT VARCHAR(16) NULL COMMENT 'Noload Speed Unit',	-- rpm

	CONSTRAINT PK_DC_MOTOR_ID PRIMARY KEY (ID),
	CONSTRAINT UK_DC_MOTOR_MODEL UNIQUE KEY (MODEL),
	CONSTRAINT FK_DC_MOTOR_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES DC_MOTOR_CATEGORY (CATEGORY),
	CONSTRAINT FK_DC_MOTOR_SERIES FOREIGN KEY (SERIES) REFERENCES DC_MOTOR_SERIES (SERIES),
	INDEX IX_DC_MOTOR_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_DC_MOTOR_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
--	INDEX IX_DC_MOTOR_NAME (NAME),
	
	INDEX IX_DC_MOTOR_CATEGORY (CATEGORY),
	INDEX IX_DC_MOTOR_SERIES (SERIES),
	
	INDEX IX_DC_MOTOR_FRAME_SIZE (FRAME_SIZE),
	INDEX IX_DC_MOTOR_NEMA_SIZE (NEMA_SIZE),
	INDEX IX_DC_MOTOR_LENGTH (LENGTH),
	INDEX IX_DC_MOTOR_WEIGHT (WEIGHT),
	
	INDEX IX_DC_MOTOR_RATED_VOLTAGE (RATED_VOLTAGE),
	INDEX IX_DC_MOTOR_RATED_CURRENT (RATED_CURRENT),
	INDEX IX_DC_MOTOR_RATED_POWER (RATED_POWER),
	INDEX IX_DC_MOTOR_RATED_TORQUE (RATED_TORQUE),
	INDEX IX_DC_MOTOR_RATED_ROTATING_SPEED (RATED_ROTATING_SPEED),
	INDEX IX_DC_MOTOR_RATED_LINEAR_SPEED (RATED_LINEAR_SPEED),
	INDEX IX_DC_MOTOR_PEAK_CURRENT (PEAK_CURRENT),
	INDEX IX_DC_MOTOR_PEAK_TORQUE (PEAK_TORQUE),
	INDEX IX_DC_MOTOR_MAX_SORTING_WEIGHT (MAX_SORTING_WEIGHT)
);

CREATE TABLE DC_MOTOR_SPEC (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	NAME VARCHAR(64) NOT NULL COMMENT 'Name',
	UNIT VARCHAR(16) NULL COMMENT 'Unit',
	VALUE VARCHAR(64) NULL COMMENT 'Value',

	CONSTRAINT PK_DC_MOTOR_SPEC_ID PRIMARY KEY (ID),
	CONSTRAINT FK_DC_MOTOR_SPEC_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES DC_MOTOR (ID),
	INDEX IX_DC_MOTOR_SPEC_NAME (NAME)
);

CREATE TABLE DC_MOTOR_PERF_MEASUREMENT (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	TITLE VARCHAR(64) NULL COMMENT 'Title',
	VARIABLES VARCHAR(512) NULL COMMENT 'Variables',
	`VALUES` VARCHAR(2048) NULL COMMENT 'Values',
	CONDITIONS VARCHAR(64) NULL COMMENT 'Conditions',

	CONSTRAINT PK_DC_MOTOR_PERF_MEASUREMENT_ID PRIMARY KEY (ID),
	CONSTRAINT FK_DC_MOTOR_PERF_MEASUREMENT_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES DC_MOTOR (ID)
);

CREATE TABLE MOTOR_CONFIG (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	MODEL_REFS VARCHAR(1024) NOT NULL COMMENT 'Model Refs',
	
	CONFIG_NAME VARCHAR(64) NOT NULL COMMENT 'Config Name',
	CONFIG_VALUE VARCHAR(1024) NULL COMMENT 'Config Value',
	
	CONSTRAINT PK_MOTOR_CONFIG_ID PRIMARY KEY (ID)
);

CREATE TABLE STEPPER_MOTOR_CATEGORY (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category',
	TYPE VARCHAR(32) NULL COMMENT 'Type',
	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name',
	DESCRIPTION VARCHAR(512) NULL COMMENT 'Description',
	TECHNICAL_DATA VARCHAR(512) NULL COMMENT 'Technical Data',
	
	CONSTRAINT PK_STEPPER_MOTOR_CATEGORY_ID PRIMARY KEY (ID),
	CONSTRAINT UK_STEPPER_MOTOR_CATEGORY_CATEGORY UNIQUE KEY (CATEGORY),
	INDEX IX_STEPPER_MOTOR_CATEGORY_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_STEPPER_MOTOR_CATEGORY_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);

CREATE TABLE STEPPER_MOTOR_SERIES (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NOT NULL COMMENT 'Series',
	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category',
	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name',
	DESCRIPTION VARCHAR(512) NULL COMMENT 'Description',
	TECHNICAL_DATA VARCHAR(512) NULL COMMENT 'Technical Data',
	
	CONSTRAINT PK_STEPPER_MOTOR_SERIES_ID PRIMARY KEY (ID),
	CONSTRAINT UK_STEPPER_MOTOR_SERIES_SERIES UNIQUE KEY (SERIES),
	CONSTRAINT FK_STEPPER_MOTOR_SERIES_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES STEPPER_MOTOR_CATEGORY (CATEGORY),
	INDEX IX_STEPPER_MOTOR_SERIES_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_STEPPER_MOTOR_SERIES_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
	INDEX IX_STEPPER_MOTOR_SERIES_CATEGORY (CATEGORY)
);


CREATE TABLE STEPPER_MOTOR (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

	CATEGORY VARCHAR(32) NOT NULL COMMENT 'Category',			-- STEPPER_STANDARD, STEPPER_FLAT, STEPPER_WITH_CONTROL
	SERIES VARCHAR(32) NULL COMMENT 'Series',
	MODEL VARCHAR(64) NOT NULL COMMENT 'Model',					-- In case of STEPPER_LINEAR, it represents MODEL instead 
	NAME VARCHAR(64) NOT NULL COMMENT 'Name',
	DESCRIPTION VARCHAR(1024) NULL COMMENT 'Description',
	
	FRAME_SIZE DECIMAL(10, 2) NULL COMMENT 'Frame Size',
	FRAME_SIZE_UNIT VARCHAR(16) NULL COMMENT 'Frame Size Unit',			-- mm, cm
	FRAME_SIZE_TYPE VARCHAR(16) NULL COMMENT 'Frame Size Type',			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE DECIMAL(8, 0) NULL COMMENT 'NEMA',
	
	LENGTH DECIMAL(10, 2) NULL COMMENT 'Motor Length',
	LENGTH_UNIT VARCHAR(16) NULL COMMENT 'Motor Length Unit',				-- mm, cm
	
	WEIGHT DECIMAL(10, 2) NULL COMMENT 'Motor Weight',
	WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Motor Weight Unit',				-- g
	
	RATED_VOLTAGE DECIMAL(10, 2) NULL COMMENT 'Rated Voltage',
	RATED_VOLTAGE_UNIT VARCHAR(16) NULL COMMENT 'Rated Voltage Unit',		-- V
	
	PHASE_CURRENT DECIMAL(10, 4) NULL COMMENT 'Phase Current',
	PHASE_CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Phase Current Unit',		-- A
	
	PHASE_RESISTANCE DECIMAL(10, 2) NULL COMMENT 'Phase Resistance',
	PHASE_RESISTANCE_UNIT VARCHAR(16) NULL COMMENT 'Phase Resistance Unit',		-- ohm (Ω)
	
	PHASE_INDUCTANCE DECIMAL(10, 2) NULL COMMENT 'Phase Inductance',
	PHASE_INDUCTANCE_UNIT VARCHAR(16) NULL COMMENT 'Phase Inductance Unit',		-- mH
	
	HOLDING_TORQUE DECIMAL(10, 4) NULL COMMENT 'Holding Torque',
	HOLDING_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Holding Torque Unit',		-- Nm, Ncm
	
	DETENT_TORQUE DECIMAL(10, 4) NULL COMMENT 'Detent Torque',
	DETENT_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Detent Torque Unit',		-- Nm, Ncm
	
	STEP_ANGLE DECIMAL(10, 2) NULL COMMENT 'Step Angle',
	STEP_ANGLE_UNIT VARCHAR(16) NULL COMMENT 'Step Angle Unit',			-- DEG (°)
	
	MAX_THRUST DECIMAL(10, 2) NULL COMMENT 'Max Thrust',
	MAX_THRUST_UNIT VARCHAR(16) NULL COMMENT 'Max Thrust Unit',			-- N
	
	CONSTRAINT PK_STEPPER_MOTOR_ID PRIMARY KEY (ID),
	CONSTRAINT UK_STEPPER_MOTOR_MODEL UNIQUE KEY (MODEL),
	CONSTRAINT FK_STEPPER_MOTOR_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES STEPPER_MOTOR_CATEGORY (CATEGORY),
	CONSTRAINT FK_STEPPER_MOTOR_SERIES FOREIGN KEY (SERIES) REFERENCES STEPPER_MOTOR_SERIES (SERIES),
	INDEX IX_STEPPER_MOTOR_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_STEPPER_MOTOR_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
--	INDEX IX_STEPPER_MOTOR_NAME (NAME),
	
	INDEX IX_STEPPER_MOTOR_CATEGORY (CATEGORY),
	INDEX IX_STEPPER_MOTOR_SERIES (SERIES),
	
	INDEX IX_STEPPER_MOTOR_FRAME_SIZE (FRAME_SIZE),
	INDEX IX_STEPPER_MOTOR_NEMA_SIZE (NEMA_SIZE),
	INDEX IX_STEPPER_MOTOR_LENGTH (LENGTH),
	INDEX IX_STEPPER_MOTOR_WEIGHT (WEIGHT),
	
	INDEX IX_STEPPER_MOTOR_RATED_VOLTAGE (RATED_VOLTAGE),
	INDEX IX_STEPPER_MOTOR_PHASE_CURRENT (PHASE_CURRENT),
	INDEX IX_STEPPER_MOTOR_HOLDING_TORQUE (HOLDING_TORQUE),
	INDEX IX_STEPPER_MOTOR_DETENT_TORQUE (DETENT_TORQUE),
	INDEX IX_STEPPER_MOTOR_STEP_ANGLE (STEP_ANGLE),
	INDEX IX_STEPPER_MOTOR_MAX_THRUST (MAX_THRUST)
);

CREATE TABLE STEPPER_MOTOR_SPEC (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	NAME VARCHAR(64) NOT NULL COMMENT 'Name',
	UNIT VARCHAR(16) NULL COMMENT 'Unit',
	VALUE VARCHAR(64) NULL COMMENT 'Value',

	CONSTRAINT PK_STEPPER_MOTOR_SPEC_ID PRIMARY KEY (ID),
	CONSTRAINT FK_STEPPER_MOTOR_SPEC_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES STEPPER_MOTOR (ID),
	INDEX IX_STEPPER_MOTOR_SPEC_NAME (NAME)
);

CREATE TABLE STEPPER_MOTOR_PERF_MEASUREMENT (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	TITLE VARCHAR(64) NULL COMMENT 'Title',
	VARIABLES VARCHAR(512) NULL COMMENT 'Variables',
	CONDITIONS VARCHAR(64) NULL COMMENT 'Conditions',
	`VALUES` VARCHAR(2048) NULL COMMENT 'Values',

	CONSTRAINT PK_STEPPER_MOTOR_PERF_MEASUREMENT_ID PRIMARY KEY (ID),
	CONSTRAINT FK_STEPPER_MOTOR_PERF_MEASUREMENT_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES STEPPER_MOTOR (ID)
);

CREATE TABLE LEAD_DEF (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	CODE VARCHAR(16) NOT NULL COMMENT 'Code',
	SCREW_DIAMETER_INCH DECIMAL(8, 4) NOT NULL COMMENT 'Screw Diameter (inch)',
	SCREW_DIAMETER_MM DECIMAL(8, 4) NOT NULL COMMENT 'Screw Diameter (mm)',
	LEAD_INCH DECIMAL(8, 4) NOT NULL COMMENT 'Lead (inch)',
	LEAD_MM DECIMAL(8, 4) NOT NULL COMMENT 'Lead (mm)',
	THREADS INT UNSIGNED NOT NULL COMMENT 'Threads',
	
	CONSTRAINT PK_LEAD_DEF_ID PRIMARY KEY (ID),
	CONSTRAINT UK_LEAD_DEF_CODE UNIQUE KEY (CODE),
	INDEX IX_LEAD_DEF_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_LEAD_DEF_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);

CREATE TABLE LINEAR_STEPPER_MOTOR_LEAD (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	MOTOR_ID INT UNSIGNED NOT NULL,
	LEAD_ID INT UNSIGNED NOT NULL,

	CONSTRAINT PK_LS_MOTOR_LEAD_ID PRIMARY KEY (ID),
	CONSTRAINT FK_LS_MOTOR_LEAD_LEAD_ID FOREIGN KEY (LEAD_ID) REFERENCES LEAD_DEF (ID),
	CONSTRAINT FK_LS_MOTOR_LEAD_MOTOR_ID FOREIGN KEY (MOTOR_ID) REFERENCES STEPPER_MOTOR (ID)
);

CREATE TABLE GEARBOX_SERIES (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NOT NULL COMMENT 'Series',
	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name',
	DESCRIPTION VARCHAR(512) NULL COMMENT 'Description',
	TECHNICAL_DATA VARCHAR(512) NULL COMMENT 'Techinical Data',
	
	CONSTRAINT PK_GEARBOX_SERIES_ID PRIMARY KEY (ID),
	CONSTRAINT UK_GEARBOX_SERIES_SERIES UNIQUE KEY (SERIES),
	INDEX IX_GEARBOX_SERIES_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_GEARBOX_SERIES_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);


CREATE TABLE PLANETARY_GEARBOX (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NULL COMMENT 'Series',
	MODEL VARCHAR(64) NOT NULL COMMENT 'Model',
	NAME VARCHAR(64) NOT NULL COMMENT 'Name',
	DESCRIPTION VARCHAR(1024) NULL COMMENT 'Description',

	FRAME_SIZE DECIMAL(10, 2) NULL COMMENT 'Frame Size',
	FRAME_SIZE_UNIT VARCHAR(16) NULL COMMENT 'Frame Size Unit',			-- mm, cm
	FRAME_SIZE_TYPE VARCHAR(16) NULL COMMENT 'Frame Size Type',			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE DECIMAL(8, 0) NULL COMMENT 'NEMA',
	
	LENGTH DECIMAL(10, 2) NULL COMMENT 'Length',
	LENGTH_UNIT VARCHAR(16) NULL COMMENT 'Length Unit',				-- mm, cm
	
	WEIGHT DECIMAL(10, 2) NULL COMMENT 'Weight',
	WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Weight Unit',				-- g

	NUM_OF_STAGES INT NOT NULL COMMENT 'Number of Stages',
	
	REDUCTION_RATIOS VARCHAR(64) NULL COMMENT 'Reduction Ratios',
		
	EFFICIENCY DECIMAL(10, 2) NULL COMMENT 'Efficency',
	EFFICIENCY_UNIT VARCHAR(16) NULL COMMENT 'Efficiency Unit',				-- PERCENT (%)

	RATED_CONTINUOUS_TORQUE DECIMAL(10, 4) NULL COMMENT 'Rated Continuous Torque',
	RATED_CONTINUOUS_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Rated Continuous Torque Unit',	-- Nm
	
	MAX_MOMENTARY_TORQUE DECIMAL(10, 4) NULL COMMENT 'Max Momentary Torque',
	MAX_MOMENTARY_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Max Momentary Torque Unit',		-- Nm
	
	MAX_RADIAL_LOAD DECIMAL(10, 2) NULL COMMENT 'Max Radial Load',
	MAX_RADIAL_LOAD_UNIT VARCHAR(16) NULL COMMENT 'Max Radial Load Unit',
	
	MAX_AXIAL_LOAD DECIMAL(10, 2) NULL COMMENT 'Max Axial Load',
	MAX_AXIAL_LOAD_UNIT VARCHAR(16) NULL COMMENT 'Max Axial Load Unit',
	
	MAX_SHAFT_PRESS DECIMAL(10, 2) NULL COMMENT 'Max Shaft Press',
	MAX_SHAFT_PRESS_UNIT VARCHAR(16) NULL COMMENT 'Max Shaft Press Unit',
	
	MAX_BACKLASH_NOLOAD DECIMAL(10, 2) NULL COMMENT 'Max Backlash Noload',
	MAX_BACKLASH_NOLOAD_UNIT VARCHAR(16) NULL COMMENT 'Max Backlash Noload Unit',
	
	OPERATING_TEMPERATURE VARCHAR(32) NULL COMMENT 'Operating Temperature',
	
	RECOMMEND_INPUT_SPEED VARCHAR(32) NULL COMMENT 'Recommended Input Speed',
	
	CONSTRAINT PK_PLANETARY_GEARBOX_ID PRIMARY KEY (ID),
	CONSTRAINT UK_PLANETARY_GEARBOX_MODEL UNIQUE KEY (MODEL),
	CONSTRAINT FK_PLANETARY_GEARBOX_SERIES FOREIGN KEY (SERIES) REFERENCES GEARBOX_SERIES (SERIES),
	INDEX IX_PLGB_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_PLGB_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
--	INDEX IX_PLGB_NAME (NAME),
	INDEX IX_PLGB_LENGTH (LENGTH),
	INDEX IX_PLGB_WEIGHT (WEIGHT),
	INDEX IX_PLGB_NUM_OF_STAGES (NUM_OF_STAGES),
	INDEX IX_PLGB_EFFICIENCY (EFFICIENCY),
	INDEX IX_PLGB_RATED_CONTINUOUS_TORQUE (RATED_CONTINUOUS_TORQUE),
	INDEX IX_PLGB_MAX_MOMENTARY_TORQUE (MAX_MOMENTARY_TORQUE)
);

CREATE TABLE BRAKE_SERIES (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NOT NULL COMMENT 'Series',
	DISPLAY_NAME VARCHAR(64) NULL COMMENT 'Display Name',
	DESCRIPTION VARCHAR(512) NULL COMMENT 'Description',
	TECHNICAL_DATA VARCHAR(256) NULL COMMENT 'Technical Data',
	
	CONSTRAINT PK_BRAKE_SERIES_ID PRIMARY KEY (ID),
	CONSTRAINT UK_BRAKE_SERIES_SERIES UNIQUE KEY (SERIES),
	INDEX IX_BRAKE_SERIES_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_BRAKE_SERIES_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP)
);


CREATE TABLE BRAKE (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
	
	SERIES VARCHAR(32) NULL COMMENT 'Series',
	MODEL VARCHAR(64) NOT NULL COMMENT 'Model',
	NAME VARCHAR(64) NOT NULL COMMENT 'Name',
	DESCRIPTION VARCHAR(1024) NULL COMMENT 'Description',

	FRAME_SIZE DECIMAL(10, 2) NULL COMMENT 'Frame Size',
	FRAME_SIZE_UNIT VARCHAR(16) NULL COMMENT 'Frame Size Unit',			-- mm, cm
	FRAME_SIZE_TYPE VARCHAR(16) NULL COMMENT 'Frame Size Type',			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE DECIMAL(8, 0) NULL COMMENT 'NEMA',
		
	LENGTH DECIMAL(10, 2) COMMENT 'Length',
	LENGTH_UNIT VARCHAR(16) COMMENT 'Length Unit',					-- mm, cm
	
	WEIGHT DECIMAL(10, 2) NULL COMMENT 'Weight',
	WEIGHT_UNIT VARCHAR(16) NULL COMMENT 'Weight Unit',				-- g
	
	RATED_VOLTAGE DECIMAL(10, 2) NULL COMMENT 'Rated Voltage',
	RATED_VOLTAGE_UNIT VARCHAR(16) NULL COMMENT 'Rated Voltage Unit',		-- V
	
	RESISTANCE DECIMAL(10, 2) NULL COMMENT 'Resistance',
	RESISTANCE_UNIT VARCHAR(16) NULL COMMENT 'Resistance Unit',			-- ohm (Ω)
	
	CURRENT DECIMAL(10, 4) NULL COMMENT 'Current',
	CURRENT_UNIT VARCHAR(16) NULL COMMENT 'Current Unit',				-- A

	STATIC_TORQUE DECIMAL(10, 4) NULL COMMENT 'Static Torque',
	STATIC_TORQUE_UNIT VARCHAR(16) NULL COMMENT 'Static Torque Unit',		-- Nm
	
	RATED_POWER DECIMAL(10, 2) NULL COMMENT 'Rated Power',
	RATED_POWER_UNIT VARCHAR(16) NULL COMMENT 'Rated Power Unit',			-- W
	
	START_VOLTAGE DECIMAL(10, 2) COMMENT 'Start Voltage',
	START_VOLTAGE_UNIT VARCHAR(16) COMMENT 'Start Voltage Unit',				-- V
	

	CONSTRAINT PK_BRAKE_ID PRIMARY KEY (ID),
	CONSTRAINT UK_BRAKE_MODEL UNIQUE KEY (MODEL),
	CONSTRAINT FK_BRAKE_SERIES FOREIGN KEY (SERIES) REFERENCES BRAKE_SERIES (SERIES),
	INDEX IX_BRAKE_CREATED_TIMESTAMP (CREATED_TIMESTAMP),
	INDEX IX_BRAKE_UPDATED_TIMESTAMP (UPDATED_TIMESTAMP),
	
--	INDEX IX_BRAKE_NAME (NAME),
	INDEX IX_BRAKE_FRAME_SIZE (FRAME_SIZE),
	INDEX IX_BRAKE_NEMA_SIZE (NEMA_SIZE),
	INDEX IX_BRAKE_LENGTH (LENGTH),
	INDEX IX_BRAKE_WEIGHT (WEIGHT),
	INDEX IX_BRAKE_RATED_VOLTAGE (RATED_VOLTAGE),
	INDEX IX_BRAKE_RESISTANCE (RESISTANCE),
	INDEX IX_BRAKE_CURRENT (CURRENT),
	INDEX IX_BRAKE_STATIC_TORQUE (STATIC_TORQUE),
	INDEX IX_BRAKE_RATED_POWER (RATED_POWER),
	INDEX IX_BRAKE_START_VOLTAGE (START_VOLTAGE)
);

CREATE TABLE INQUIRY (
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	VERSION INT UNSIGNED NULL DEFAULT 0,
	CREATED_TIMESTAMP DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_TIMESTAMP DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,

	CONTACT_NAME VARCHAR(64) NULL COMMENT 'Contact Name',
	CONTACT_EMAIL VARCHAR(64) NULL COMMENT 'Contact Email',
	CONTACT_PHONE VARCHAR(64) NULL COMMENT 'Contact Phone',
	REF_MODEL VARCHAR(64) NULL COMMENT 'Ref Model',
	QUANTITY INT UNSIGNED NULL COMMENT 'Quantity',
	MESSAGE VARCHAR(1024) NULL COMMENT 'Message',
	REF_LINK VARCHAR(256) NULL COMMENT 'Ref Link',
	CLIENT_IP_ADDRESS VARCHAR(64) NULL COMMENT 'Client IP Address',
	CLIENT_COUNTRY_OR_REGION VARCHAR(64) NULL COMMENT 'Client Country or Region',
	STATUS VARCHAR(32) NULL COMMENT 'Status',
	
	CONSTRAINT PK_INQUIRY_ID PRIMARY KEY (ID),
	
	INDEX IX_INQUIRY_REF_MODEL (REF_MODEL)
);
