SET @series := 'SE060AS';
SET @model  := 'SE060AS100';

INSERT INTO DC_MOTOR (
	CATEGORY,					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	SERIES,
	MODEL,
	NAME,
	DESCRIPTION,
	
	FRAME_SIZE,
	FRAME_SIZE_UNIT,			-- mm, cm
	FRAME_SIZE_TYPE,			-- DIAMETER, SIDE
	NEMA_SIZE,
	
	LENGTH,
	LENGTH_UNIT,				-- mm, cm
	
	WEIGHT,
	WEIGHT_UNIT,				-- g

	RATED_VOLTAGE,
	RATED_VOLTAGE_UNIT,		-- V

	RATED_CURRENT,
	RATED_CURRENT_UNIT,		-- A

	RATED_POWER,
	RATED_POWER_UNIT,			-- W

	RATED_TORQUE,
	RATED_TORQUE_UNIT,			-- Nm
	
	RATED_ROTATING_SPEED,
	RATED_ROTATING_SPEED_UNIT,	-- rpm
	
	RATED_LINEAR_SPEED,
	RATED_LINEAR_SPEED_UNIT,	-- mps

	PEAK_CURRENT,
	PEAK_CURRENT_UNIT,			-- A

	PEAK_TORQUE,
	PEAK_TORQUE_UNIT,			-- Nm

	MAX_SORTING_WEIGHT,
	MAX_SORTING_WEIGHT_UNIT,	-- kg

	NOLOAD_CURRENT,
	NOLOAD_CURRENT_UNIT,		-- mA

	NOLOAD_ROTATING_SPEED,
	NOLOAD_ROTATING_SPEED_UNIT	-- rpm
)
VALUES (
	'BLDC_SERVO', 			-- CATEGORY					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	@series,						-- SERIES
	@model,							-- MODEL
	'BLDC Servo Motor',				-- NAME
	NULL,							-- DESCRIPTION
	
	60,								-- FRAME_SIZE
	'mm',							-- FRAME_SIZE_UNIT			-- mm, cm
	'□',							-- FRAME_SIZE_TYPE			-- DIAMETER(φ), SIDE(□)
	NULL,							-- NEMA_SIZE
	
	101,							-- LENGTH
	'mm',							-- LENGTH_UNIT				-- mm, cm
	
	0.85,							-- WEIGHT
	'kg',							-- WEIGHT_UNIT				-- g, kg

	36,								-- RATED_VOLTAGE
	'V',							-- RATED_VOLTAGE_UNIT		-- V

	3.7,							-- RATED_CURRENT
	'A',							-- RATED_CURRENT_UNIT		-- A

	100,							-- RATED_POWER
	'W',							-- RATED_POWER_UNIT			-- W

	0.32,							-- RATED_TORQUE
	'Nm',							-- RATED_TORQUE_UNIT			-- Nm
	
	3000,							-- RATED_ROTATING_SPEED
	'rpm',							-- RATED_ROTATING_SPEED_UNIT	-- rpm
	
	NULL,							-- RATED_LINEAR_SPEED
	NULL,							-- RATED_LINEAR_SPEED_UNIT	-- mps

	11.1,							-- PEAK_CURRENT
	'A',							-- PEAK_CURRENT_UNIT			-- A

	0.96,							-- PEAK_TORQUE
	'Nm',							-- PEAK_TORQUE_UNIT			-- Nm

	NULL,							-- MAX_SORTING_WEIGHT
	NULL,							-- MAX_SORTING_WEIGHT_UNIT	-- kg

	NULL,							-- NOLOAD_CURRENT
	NULL,							-- NOLOAD_CURRENT_UNIT		-- mA

	NULL,							-- NOLOAD_ROTATING_SPEED
	NULL							-- NOLOAD_ROTATING_SPEED_UNIT	-- rpm
);


INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Torque Constant', 'Nm/A', '0.057' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Ke(RMS)', 'V/krpm', '4.2' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Resistance', 'Ω', '0.64' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Inductance', 'mH', '0.5' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Rotor Inertia', 'Kg.cm²', '0.1' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'No. of Poles', NULL, '8' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Feedback Device (Optical encoder)', 'PPR', '2500' FROM DC_MOTOR WHERE MODEL = @model
;


INSERT INTO DC_MOTOR_PERF_MEASUREMENT (MOTOR_ID, TITLE, VARIABLES, `VALUES`)
SELECT ID, CONCAT(@model, ' @ 48 Vdc'), 'Torque(Nm), Speed(rpm), Torque(Nm), Speed(rpm)',
'1.92,0,0.64,0
1.92,2300,0.64,4200
0.64,4200,,
0,5000,,
'
FROM DC_MOTOR WHERE MODEL = @model
;
