SET @series := 'LS020NB';
SET @model  := 'LS020NB101';

INSERT INTO STEPPER_MOTOR  (
	CATEGORY,						-- STEPPER_STANDARD, STEPPER_FLAT, STEPPER_WITH_CONTROL
	SERIES,
	MODEL,						-- In case of STEPPER_LINEAR, it represents MODEL instead 
	NAME,
	DESCRIPTION, 
	
	FRAME_SIZE,
	FRAME_SIZE_UNIT,			-- mm, cm
	FRAME_SIZE_TYPE,			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE,
	
	LENGTH,
	LENGTH_UNIT,				-- mm, cm
	
	WEIGHT,
	WEIGHT_UNIT,				-- g
	
	RATED_VOLTAGE,
	RATED_VOLTAGE_UNIT,			-- V
	
	PHASE_CURRENT,
	PHASE_CURRENT_UNIT,			-- A
	
	PHASE_RESISTANCE,
	PHASE_RESISTANCE_UNIT,		-- ohm (Ω)
	
	PHASE_INDUCTANCE,
	PHASE_INDUCTANCE_UNIT,		-- mH
	
	HOLDING_TORQUE,
	HOLDING_TORQUE_UNIT,		-- Nm, Ncm
	
	DETENT_TORQUE,
	DETENT_TORQUE_UNIT,			-- Nm, Ncm
	
	STEP_ANGLE,
	STEP_ANGLE_UNIT,			-- DEG (°)
	
	MAX_THRUST,
	MAX_THRUST_UNIT				-- N
)
VALUES (
	'STEPPER_LINEAR',			-- CATEGORY						-- STEPPER_STANDARD, STEPPER_FLAT, STEPPER_WITH_CONTROL
	@series,					-- SERIES
	@model,						-- MODEL					-- In case of STEPPER_LINEAR, it represents MODEL instead 
	'Linear Stepper Motor',		-- NAME
	NULL,						-- DESCRIPTION 
	
	20,							-- FRAME_SIZE
	'mm',						-- FRAME_SIZE_UNIT			-- mm, cm
	'□',						-- FRAME_SIZE_TYPE			-- DIAMETER, SIDE
	8,							-- NEMA_SIZE
	
	27.2,						-- LENGTH
	'mm',						-- LENGTH_UNIT				-- mm, cm
	
	NULL,							-- WEIGHT
	NULL,						-- WEIGHT_UNIT				-- g
	
	2.5,						-- RATED_VOLTAGE
	'V',						-- RATED_VOLTAGE_UNIT		-- V
	
	0.5,							-- PHASE_CURRENT
	'A',						-- PHASE_CURRENT_UNIT		-- A
	
	5.1,						-- PHASE_RESISTANCE
	'Ω',						-- PHASE_RESISTANCE_UNIT	-- ohm (Ω)
	
	1.5,						-- PHASE_INDUCTANCE
	'mH',						-- PHASE_INDUCTANCE_UNIT	-- mH
	
	NULL,						-- HOLDING_TORQUE
	NULL,						-- HOLDING_TORQUE_UNIT		-- Nm, Ncm
	
	NULL,						-- DETENT_TORQUE
	NULL,						-- DETENT_TORQUE_UNIT		-- Nm, Ncm
	
	NULL,						-- STEP_ANGLE
	NULL,						-- STEP_ANGLE_UNIT			-- DEG (°)
	
	65,						-- MAX_THRUST
	'N'						-- MAX_THRUST_UNIT			-- N
);


INSERT INTO LINEAR_STEPPER_MOTOR_LEAD (MOTOR_ID, LEAD_ID)
SELECT sm.ID, ld.ID FROM STEPPER_MOTOR sm, LEAD_DEF ld 
WHERE sm.MODEL = @model AND (ld.CODE = 'B0024' OR ld.CODE = 'B0048' OR ld.CODE = 'B0079' OR ld.CODE = 'B0157' OR ld.CODE = 'B0315')
;

INSERT INTO STEPPER_MOTOR_PERF_MEASUREMENT (MOTOR_ID, TITLE, VARIABLES, CONDITIONS, `VALUES`)
SELECT ID, CONCAT(@model, ' Speed-Thrust Curves'), 'pps, r/min, LinearSpeed[0.3048:AF, 0.6096:AA, 1.2192:B, 2:G, 4:M, 8:T](mm/s), Thrust[0.3048:AF, 0.6096:AA, 1.2192:B, 2:G, 4:M, 8:T](kg)', '',
'200,60,0.3,0.6,1.2,2.0,4.0,8.0,3.2,2.7,2.2,2.1,1.1,0.5 
600,180,0.9,1.8,3.7,6.0,12.0,24.0,3.1,2.5,2.1,2.0,0.9,0.4 
1000,300,1.5,3.0,6.1,10.0,20.0,40.0,2.8,2.4,2.0,1.9,0.9,0.4 
1500,450,2.3,4.6,9.1,15.0,30.0,60.0,2.7,2.4,1.9,1.8,0.6,0.3 
2000,600,3.0,6.1,12.2,20.0,40.0,80.0,2.6,2.2,1.8,1.7,0.6,0.2 
2500,750,3.8,7.6,15.2,25.0,50.0,100.0,2.5,1.9,1.7,1.5,0.5,0.2  
'
FROM STEPPER_MOTOR WHERE MODEL = @model
;