SET @series := 'MB057GA';
SET @model  := 'MB057GA400';

INSERT INTO DC_MOTOR (
	CATEGORY,					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	SERIES,
	MODEL,
	NAME,
	DESCRIPTION, 
	
	FRAME_SIZE,
	FRAME_SIZE_UNIT,			-- mm, cm
	FRAME_SIZE_TYPE,			-- DIAMETER, SIDE
	NEMA_SIZE,
	
	LENGTH,
	LENGTH_UNIT,				-- mm, cm
	
	WEIGHT,
	WEIGHT_UNIT,				-- g

	RATED_VOLTAGE,
	RATED_VOLTAGE_UNIT,		-- V

	RATED_CURRENT,
	RATED_CURRENT_UNIT,		-- A

	RATED_POWER,
	RATED_POWER_UNIT,			-- W

	RATED_TORQUE,
	RATED_TORQUE_UNIT,			-- Nm
	
	RATED_ROTATING_SPEED,
	RATED_ROTATING_SPEED_UNIT,	-- rpm
	
	RATED_LINEAR_SPEED,
	RATED_LINEAR_SPEED_UNIT,	-- mps

	PEAK_CURRENT,
	PEAK_CURRENT_UNIT,			-- A

	PEAK_TORQUE,
	PEAK_TORQUE_UNIT,			-- Nm

	MAX_SORTING_WEIGHT,
	MAX_SORTING_WEIGHT_UNIT,	-- kg

	NOLOAD_CURRENT,
	NOLOAD_CURRENT_UNIT,		-- mA

	NOLOAD_ROTATING_SPEED,
	NOLOAD_ROTATING_SPEED_UNIT	-- rpm
)
VALUES (
	'BLDC_INTERNAL_ROTOR', 			-- CATEGORY					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	@series,						-- SERIES
	@model,							-- MODEL
	'Internal Rotor BLDC Motor',	-- NAME
	NULL,							-- DESCRIPTION 
	
	57,								-- FRAME_SIZE
	'mm',							-- FRAME_SIZE_UNIT			-- mm, cm
	'φ',							-- FRAME_SIZE_TYPE			-- DIAMETER, SIDE
	23,								-- NEMA_SIZE
	
	114,							-- LENGTH
	'mm',							-- LENGTH_UNIT				-- mm, cm
	
	1.25,							-- WEIGHT
	'kg',							-- WEIGHT_UNIT				-- g, kg

	60,								-- RATED_VOLTAGE
	'V',							-- RATED_VOLTAGE_UNIT		-- V

	4.6,							-- RATED_CURRENT
	'A',							-- RATED_CURRENT_UNIT		-- A

	209,							-- RATED_POWER
	'W',							-- RATED_POWER_UNIT			-- W

	0.4,							-- RATED_TORQUE
	'Nm',							-- RATED_TORQUE_UNIT			-- Nm
	
	5000,							-- RATED_ROTATING_SPEED
	'rpm',							-- RATED_ROTATING_SPEED_UNIT	-- rpm
	
	NULL,							-- RATED_LINEAR_SPEED
	NULL,							-- RATED_LINEAR_SPEED_UNIT	-- mps

	13.8,							-- PEAK_CURRENT
	'A',							-- PEAK_CURRENT_UNIT			-- A

	1.2,							-- PEAK_TORQUE
	'Nm',							-- PEAK_TORQUE_UNIT			-- Nm

	NULL,							-- MAX_SORTING_WEIGHT
	NULL,							-- MAX_SORTING_WEIGHT_UNIT	-- kg

	NULL,							-- NOLOAD_CURRENT
	NULL,							-- NOLOAD_CURRENT_UNIT		-- mA

	NULL,							-- NOLOAD_ROTATING_SPEED
	NULL							-- NOLOAD_ROTATING_SPEED_UNIT	-- rpm
);

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Torque Constant', 'Nm/A', '0.077' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Ke(RMS)', 'V/krpm', '5.7' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Rotor Inertia', 'Kg.cm²', '0.328' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Resistance', 'Ω', '0.49' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Inductance', 'mH', '1.6' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_PERF_MEASUREMENT (MOTOR_ID, TITLE, VARIABLES, `VALUES`)
SELECT ID, CONCAT(@model, ' @ 60 Vdc'), 'Speed(Krpm), Torque(oz-in), Torque(Ncm)',
'0.000,74.591,134.40
0.417,73.886,133.07
0.625,73.487,131.69
1.042,72.593,128.64
1.458,71.569,125.14
1.875,70.408,121.08
2.083,69.774,118.79
2.292,69.103,116.30
2.500,68.394,113.58
2.708,67.646,110.60
2.917,66.858,107.32
3.125,66.028,103.69
3.542,64.235,95.13
3.750,63.268,90.03
4.167,61.185,77.61
4.375,60.063,70.02
4.792,57.641,55.82
5.000,56.334,49.51
'
FROM DC_MOTOR WHERE MODEL = @model
;
