SET @series := 'MB059AH';
SET @model  := 'MB059AH200';

INSERT INTO DC_MOTOR (
	CATEGORY,					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	SERIES,
	MODEL,
	NAME,
	DESCRIPTION,
	
	FRAME_SIZE,
	FRAME_SIZE_UNIT,			-- mm, cm
	FRAME_SIZE_TYPE,			-- DIAMETER(φ), SIDE
	NEMA_SIZE,
	
	LENGTH,
	LENGTH_UNIT,				-- mm, cm
	
	WEIGHT,
	WEIGHT_UNIT,				-- g

	RATED_VOLTAGE,
	RATED_VOLTAGE_UNIT,		-- V

	RATED_CURRENT,
	RATED_CURRENT_UNIT,		-- A

	RATED_POWER,
	RATED_POWER_UNIT,			-- W

	RATED_TORQUE,
	RATED_TORQUE_UNIT,			-- Nm
	
	RATED_ROTATING_SPEED,
	RATED_ROTATING_SPEED_UNIT,	-- rpm
	
	RATED_LINEAR_SPEED,
	RATED_LINEAR_SPEED_UNIT,	-- mps

	PEAK_CURRENT,
	PEAK_CURRENT_UNIT,			-- A

	PEAK_TORQUE,
	PEAK_TORQUE_UNIT,			-- Nm

	MAX_SORTING_WEIGHT,
	MAX_SORTING_WEIGHT_UNIT,	-- kg

	NOLOAD_CURRENT,
	NOLOAD_CURRENT_UNIT,		-- mA

	NOLOAD_ROTATING_SPEED,
	NOLOAD_ROTATING_SPEED_UNIT	-- rpm
)
VALUES (
	'BLDC_INTERNAL_ROTOR', 			-- CATEGORY					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	@series,						-- SERIES
	@model,							-- MODEL
	'Internal Rotor BLDC Motor',	-- NAME
	NULL,							-- DESCRIPTION 
	
	57,								-- FRAME_SIZE
	'mm',							-- FRAME_SIZE_UNIT			-- mm, cm
	'φ',							-- FRAME_SIZE_TYPE			-- DIAMETER, SIDE
	NULL,							-- NEMA_SIZE
	
	68.6,							-- LENGTH
	'mm',							-- LENGTH_UNIT				-- mm, cm
	
	0.65,							-- WEIGHT
	'kg',							-- WEIGHT_UNIT				-- g, kg

	24,								-- RATED_VOLTAGE
	'V',							-- RATED_VOLTAGE_UNIT		-- V

	7.5,							-- RATED_CURRENT
	'A',							-- RATED_CURRENT_UNIT		-- A

	136,							-- RATED_POWER
	'W',							-- RATED_POWER_UNIT			-- W

	0.37,							-- RATED_TORQUE
	'Nm',							-- RATED_TORQUE_UNIT			-- Nm
	
	3500,							-- RATED_ROTATING_SPEED
	'rpm',							-- RATED_ROTATING_SPEED_UNIT	-- rpm
	
	NULL,							-- RATED_LINEAR_SPEED
	NULL,							-- RATED_LINEAR_SPEED_UNIT	-- mps

	22.5,							-- PEAK_CURRENT
	'A',							-- PEAK_CURRENT_UNIT			-- A

	1.11,							-- PEAK_TORQUE
	'Nm',							-- PEAK_TORQUE_UNIT			-- Nm

	NULL,							-- MAX_SORTING_WEIGHT
	NULL,							-- MAX_SORTING_WEIGHT_UNIT	-- kg

	NULL,							-- NOLOAD_CURRENT
	NULL,							-- NOLOAD_CURRENT_UNIT		-- mA

	NULL,							-- NOLOAD_ROTATING_SPEED
	NULL							-- NOLOAD_ROTATING_SPEED_UNIT	-- rpm
);

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Torque Constant', 'Nm/A', '0.048' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Ke(RMS)', 'V/krpm', '3.5' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Rotor Inertia', 'Kg.cm²', '0.105' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Resistance', 'Ω', '0.24' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Inductance', 'mH', '0.29' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Insulation Class', NULL, 'B' FROM DC_MOTOR WHERE MODEL = @model
;


INSERT INTO DC_MOTOR_PERF_MEASUREMENT (MOTOR_ID, TITLE, VARIABLES, `VALUES`)
SELECT ID, CONCAT(@model, ' @ 24 Vdc'), 'Torque(Nm), Current(A), Speed(rpm)',
'0,0.70,4700
0.062,1.79,4499
0.12,2.81,4311
0.18,3.86,4116
0.25,5.09,3889
0.31,6.15,3695
0.37,7.20,3500
0.42,8.08,3338
0.49,9.31,3111
0.55,10.36,2916
0.61,11.42,2722
0.67,12.47,2527
0.73,13.52,2333
0.79,14.58,2138
0.85,15.63,1943
'
FROM DC_MOTOR WHERE MODEL = @model
;
