SET @series := 'MB070GA';
SET @model  := 'MB070GA100';

INSERT INTO DC_MOTOR (
	CATEGORY,					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	SERIES,
	MODEL,
	NAME,
	DESCRIPTION,
	
	FRAME_SIZE,
	FRAME_SIZE_UNIT,			-- mm, cm
	FRAME_SIZE_TYPE,			-- DIAMETER, SIDE
	NEMA_SIZE,
	
	LENGTH,
	LENGTH_UNIT,				-- mm, cm
	
	WEIGHT,
	WEIGHT_UNIT,				-- g

	RATED_VOLTAGE,
	RATED_VOLTAGE_UNIT,		-- V

	RATED_CURRENT,
	RATED_CURRENT_UNIT,		-- A

	RATED_POWER,
	RATED_POWER_UNIT,			-- W

	RATED_TORQUE,
	RATED_TORQUE_UNIT,			-- Nm
	
	RATED_ROTATING_SPEED,
	RATED_ROTATING_SPEED_UNIT,	-- rpm
	
	RATED_LINEAR_SPEED,
	RATED_LINEAR_SPEED_UNIT,	-- mps

	PEAK_CURRENT,
	PEAK_CURRENT_UNIT,			-- A

	PEAK_TORQUE,
	PEAK_TORQUE_UNIT,			-- Nm

	MAX_SORTING_WEIGHT,
	MAX_SORTING_WEIGHT_UNIT,	-- kg

	NOLOAD_CURRENT,
	NOLOAD_CURRENT_UNIT,		-- mA

	NOLOAD_ROTATING_SPEED,
	NOLOAD_ROTATING_SPEED_UNIT	-- rpm
)
VALUES (
	'BLDC_INTERNAL_ROTOR', 			-- CATEGORY					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	@series,						-- SERIES
	@model,							-- MODEL
	'Internal Rotor BLDC Motor',	-- NAME
	NULL,							-- DESCRIPTION
	
	70,								-- FRAME_SIZE
	'mm',							-- FRAME_SIZE_UNIT			-- mm, cm
	'φ',							-- FRAME_SIZE_TYPE			-- DIAMETER, SIDE
	NULL,							-- NEMA_SIZE
	
	95,								-- LENGTH
	'mm',							-- LENGTH_UNIT				-- mm, cm
	
	1,							-- WEIGHT
	'kg',							-- WEIGHT_UNIT				-- g, kg

	24,								-- RATED_VOLTAGE
	'V',							-- RATED_VOLTAGE_UNIT		-- V

	4.3,							-- RATED_CURRENT
	'A',							-- RATED_CURRENT_UNIT		-- A

	85,							-- RATED_POWER
	'W',							-- RATED_POWER_UNIT			-- W

	0.215,							-- RATED_TORQUE
	'Nm',							-- RATED_TORQUE_UNIT			-- Nm
	
	3800,							-- RATED_ROTATING_SPEED
	'rpm',							-- RATED_ROTATING_SPEED_UNIT	-- rpm
	
	NULL,							-- RATED_LINEAR_SPEED
	NULL,							-- RATED_LINEAR_SPEED_UNIT	-- mps

	NULL,							-- PEAK_CURRENT
	NULL,							-- PEAK_CURRENT_UNIT			-- A

	NULL,							-- PEAK_TORQUE
	NULL,							-- PEAK_TORQUE_UNIT			-- Nm

	NULL,							-- MAX_SORTING_WEIGHT
	NULL,							-- MAX_SORTING_WEIGHT_UNIT	-- kg

	0.75,							-- NOLOAD_CURRENT
	'A',							-- NOLOAD_CURRENT_UNIT		-- mA

	4760,							-- NOLOAD_ROTATING_SPEED
	'rpm'							-- NOLOAD_ROTATING_SPEED_UNIT	-- rpm
);

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Max. Continuous Torque', 'Nm', '0.3' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Max. Continuous Current', 'A', '5.8' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Rotor Inertia', 'Kg.cm²', '0.3' FROM DC_MOTOR WHERE MODEL = @model
;


