SET @series := 'MB059AH';
SET @model  := 'MB059AH400';

INSERT INTO DC_MOTOR (
	CATEGORY,					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	SERIES,
	MODEL,
	NAME,
	DESCRIPTION,
	
	FRAME_SIZE,
	FRAME_SIZE_UNIT,			-- mm, cm
	FRAME_SIZE_TYPE,			-- DIAMETER(φ), SIDE
	NEMA_SIZE,
	
	LENGTH,
	LENGTH_UNIT,				-- mm, cm
	
	WEIGHT,
	WEIGHT_UNIT,				-- g

	RATED_VOLTAGE,
	RATED_VOLTAGE_UNIT,		-- V

	RATED_CURRENT,
	RATED_CURRENT_UNIT,		-- A

	RATED_POWER,
	RATED_POWER_UNIT,			-- W

	RATED_TORQUE,
	RATED_TORQUE_UNIT,			-- Nm
	
	RATED_ROTATING_SPEED,
	RATED_ROTATING_SPEED_UNIT,	-- rpm
	
	RATED_LINEAR_SPEED,
	RATED_LINEAR_SPEED_UNIT,	-- mps

	PEAK_CURRENT,
	PEAK_CURRENT_UNIT,			-- A

	PEAK_TORQUE,
	PEAK_TORQUE_UNIT,			-- Nm

	MAX_SORTING_WEIGHT,
	MAX_SORTING_WEIGHT_UNIT,	-- kg

	NOLOAD_CURRENT,
	NOLOAD_CURRENT_UNIT,		-- mA

	NOLOAD_ROTATING_SPEED,
	NOLOAD_ROTATING_SPEED_UNIT	-- rpm
)
VALUES (
	'BLDC_INTERNAL_ROTOR', 			-- CATEGORY					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	@series,						-- SERIES
	@model,							-- MODEL
	'Internal Rotor BLDC Motor',	-- NAME
	NULL,							-- DESCRIPTION
	
	57,								-- FRAME_SIZE
	'mm',							-- FRAME_SIZE_UNIT			-- mm, cm
	'φ',							-- FRAME_SIZE_TYPE			-- DIAMETER, SIDE
	NULL,							-- NEMA_SIZE
	
	93.6,							-- LENGTH
	'mm',							-- LENGTH_UNIT				-- mm, cm
	
	0.95,							-- WEIGHT
	'kg',							-- WEIGHT_UNIT				-- g, kg

	24,								-- RATED_VOLTAGE
	'V',							-- RATED_VOLTAGE_UNIT		-- V

	12.2,							-- RATED_CURRENT
	'A',							-- RATED_CURRENT_UNIT		-- A

	220,							-- RATED_POWER
	'W',							-- RATED_POWER_UNIT			-- W

	0.60,							-- RATED_TORQUE
	'Nm',							-- RATED_TORQUE_UNIT			-- Nm
	
	3500,							-- RATED_ROTATING_SPEED
	'rpm',							-- RATED_ROTATING_SPEED_UNIT	-- rpm
	
	NULL,							-- RATED_LINEAR_SPEED
	NULL,							-- RATED_LINEAR_SPEED_UNIT	-- mps

	36.6,							-- PEAK_CURRENT
	'A',							-- PEAK_CURRENT_UNIT			-- A

	1.80,							-- PEAK_TORQUE
	'Nm',							-- PEAK_TORQUE_UNIT			-- Nm

	NULL,							-- MAX_SORTING_WEIGHT
	NULL,							-- MAX_SORTING_WEIGHT_UNIT	-- kg

	NULL,							-- NOLOAD_CURRENT
	NULL,							-- NOLOAD_CURRENT_UNIT		-- mA

	NULL,							-- NOLOAD_ROTATING_SPEED
	NULL							-- NOLOAD_ROTATING_SPEED_UNIT	-- rpm
);

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Torque Constant', 'Nm/A', '0.050' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Ke(RMS)', 'V/krpm', '3.7' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Rotor Inertia', 'Kg.cm²', '0.173' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Resistance', 'Ω', '0.14' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Inductance', 'mH', '0.20' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Insulation Class', NULL, 'B' FROM DC_MOTOR WHERE MODEL = @model
;


INSERT INTO DC_MOTOR_PERF_MEASUREMENT (MOTOR_ID, TITLE, VARIABLES, `VALUES`)
SELECT ID, CONCAT(@model, ' @ 24 Vdc'), 'Torque(Nm), Current(A), Speed(rpm)',
'0.00,0.8,4360
0.10,2.5,4179
0.21,4.3,4002
0.30,5.9,3838
0.40,7.6,3662
0.50,9.3,3488
0.60,10.8,3316
0.70,12.6,3137
0.80,14.3,2968
0.90,15.9,2794
1.03,18,2577
'
FROM DC_MOTOR WHERE MODEL = @model
;
