SET @series := 'MB057GA';
SET @model  := 'MB057GA200';

INSERT INTO DC_MOTOR (
	CATEGORY,					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	SERIES,
	MODEL,
	NAME,
	DESCRIPTION, 
	
	FRAME_SIZE,
	FRAME_SIZE_UNIT,			-- mm, cm
	FRAME_SIZE_TYPE,			-- DIAMETER, SIDE
	NEMA_SIZE,
	
	LENGTH,
	LENGTH_UNIT,				-- mm, cm
	
	WEIGHT,
	WEIGHT_UNIT,				-- g

	RATED_VOLTAGE,
	RATED_VOLTAGE_UNIT,		-- V

	RATED_CURRENT,
	RATED_CURRENT_UNIT,		-- A

	RATED_POWER,
	RATED_POWER_UNIT,			-- W

	RATED_TORQUE,
	RATED_TORQUE_UNIT,			-- Nm
	
	RATED_ROTATING_SPEED,
	RATED_ROTATING_SPEED_UNIT,	-- rpm
	
	RATED_LINEAR_SPEED,
	RATED_LINEAR_SPEED_UNIT,	-- mps

	PEAK_CURRENT,
	PEAK_CURRENT_UNIT,			-- A

	PEAK_TORQUE,
	PEAK_TORQUE_UNIT,			-- Nm

	MAX_SORTING_WEIGHT,
	MAX_SORTING_WEIGHT_UNIT,	-- kg

	NOLOAD_CURRENT,
	NOLOAD_CURRENT_UNIT,		-- mA

	NOLOAD_ROTATING_SPEED,
	NOLOAD_ROTATING_SPEED_UNIT	-- rpm
)
VALUES (
	'BLDC_INTERNAL_ROTOR', 			-- CATEGORY					-- BLDC_INTERNAL_ROTOR, BLDC_EXTERNAL_ROTOR, BLDC_FRAMELESS, BLDC_SERVO, BLDC_CORELESS, BLDC_DIRECT_DRIVE, PM_DC, INTEGRATED
	@series,						-- SERIES
	@model,							-- MODEL
	'Internal Rotor BLDC Motor',	-- NAME
	NULL,							-- DESCRIPTION 
	
	57,								-- FRAME_SIZE
	'mm',							-- FRAME_SIZE_UNIT			-- mm, cm
	'φ',							-- FRAME_SIZE_TYPE			-- DIAMETER, SIDE
	23,								-- NEMA_SIZE
	
	74,								-- LENGTH
	'mm',							-- LENGTH_UNIT				-- mm, cm
	
	0.75,							-- WEIGHT
	'kg',							-- WEIGHT_UNIT				-- g, kg

	60,								-- RATED_VOLTAGE
	'V',							-- RATED_VOLTAGE_UNIT		-- V

	2.3,							-- RATED_CURRENT
	'A',							-- RATED_CURRENT_UNIT		-- A

	105,							-- RATED_POWER
	'W',							-- RATED_POWER_UNIT			-- W

	0.2,							-- RATED_TORQUE
	'Nm',							-- RATED_TORQUE_UNIT			-- Nm
	
	5000,							-- RATED_ROTATING_SPEED
	'rpm',							-- RATED_ROTATING_SPEED_UNIT	-- rpm
	
	NULL,							-- RATED_LINEAR_SPEED
	NULL,							-- RATED_LINEAR_SPEED_UNIT	-- mps

	6.9,							-- PEAK_CURRENT
	'A',							-- PEAK_CURRENT_UNIT			-- A

	0.6,							-- PEAK_TORQUE
	'Nm',							-- PEAK_TORQUE_UNIT			-- Nm

	NULL,							-- MAX_SORTING_WEIGHT
	NULL,							-- MAX_SORTING_WEIGHT_UNIT	-- kg

	NULL,							-- NOLOAD_CURRENT
	NULL,							-- NOLOAD_CURRENT_UNIT		-- mA

	NULL,							-- NOLOAD_ROTATING_SPEED
	NULL							-- NOLOAD_ROTATING_SPEED_UNIT	-- rpm
);

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Torque Constant', 'Nm/A', '0.084' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Ke(RMS)', 'V/krpm', '6.2' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Rotor Inertia', 'Kg.cm²', '0.169' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Resistance', 'Ω', '1.79' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Line to Line Inductance', 'mH', '3.16' FROM DC_MOTOR WHERE MODEL = @model
;

INSERT INTO DC_MOTOR_PERF_MEASUREMENT (MOTOR_ID, TITLE, VARIABLES, `VALUES`)
SELECT ID, CONCAT(@model, ' @ 60 Vdc'), 'Speed(Krpm), Torque(oz-in), Torque(Ncm)',
'0, 40.363, 79.593
0.5, 39.895, 78.455
0.75, 39.636, 77.255
1, 39.360, 75.938
1.5, 38.757, 72.872
1.75, 38.428, 71.073
2, 38.080, 69.052
2.25, 37.714, 66.764
2.75, 36.921, 61.140
3, 36.494, 57.626
3.25, 36.045, 53.467
3.5, 35.573, 48.459
3.75, 35.078, 42.700
4.25, 34.014, 32.529
4.75, 32.842, 24.040
5, 28.753, 20.304
5.5, 19.346, 13.661
6, 11.239, 7.936
'
FROM DC_MOTOR WHERE MODEL = @model;
