-- Begin to set up Safe Threashold for BLDC_INTERNAL_ROTOR motors --
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.23,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB059AH100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.37,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB059AH200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.47,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB059AH300');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.60,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB059AH400');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.15,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MDB56GS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.3,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MDB56GS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.45,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MDB56GS300');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.6,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MDB56GS400');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.09,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042AS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.201,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042AS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.34,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042AS300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.06,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042GS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.13,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042GS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.19,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042GS300');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.3,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042GS400');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.080,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042YS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.150,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME042YS200');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.04,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME043AS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.078,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME043AS300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.314,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME057AH100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.552,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME057AH200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.645,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME057AH300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.25,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME060AS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.50,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME060AS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.75,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME060AS300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.50,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME070AS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME070AS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1.52,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME070AS300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME080AS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1.5,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME080AS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '2,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME080AS300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.5,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME080RS100D');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME080RS200D');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.8,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME080RS210D');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1.53,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME080RS300D');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.7,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME086AS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1.5,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME086AS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '2,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME086AS300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '2,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME110AS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '4,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME110AS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '6,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'ME110AS300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.23,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MEL57AH100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.46,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MEL57AH200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.7,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MEL57AH300');
-- End to set up Safe Threashold for BLDC_INTERNAL_ROTOR motors --


-- Begin to set up Safe Threashold for BLDC_SERVO motors --
-- End to set up Safe Threashold for BLDC_SERVO motors --


-- Begin to set up Safe Threashold for BRUSH motors --
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '11.3,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB030JS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '16.9,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB040JS100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '32.6,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB040JS200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '43.1,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB040JS300');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '49,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB040JS400');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '66.9,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB040JS500');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '80.6,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB040JS600');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '39.8,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB042DK100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '75.8,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB042DK200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '90.1,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB042DK300');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.07,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB054TP100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.243,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB054TP300');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.26,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB054TP600');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.362,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB054TP700');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '108.1,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB063KG100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '106.7,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB063KG150');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '311,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB063KG200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '198.8,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB063KG250');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.93,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB076HG200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.75,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB076HG210');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.78,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB076HG220');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.80,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB076HG230');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1.39,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB076HG400');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1.32,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB076HG410');

UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '0.90,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB100FG100');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '1.60,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB100FG200');
UPDATE DC_MOTOR_PERF_MEASUREMENT SET SAFE_THRESHOLD = '2.10,_,_' WHERE MOTOR_ID = (SELECT ID FROM DC_MOTOR dm WHERE dm.MODEL = 'MB100FG300');
-- End to set up Safe Threashold for BRUSH motors --

