SET @series := 'MP028NB';
SET @model  := 'MP028NB301';

INSERT INTO STEPPER_MOTOR  (
	CATEGORY,						-- STEPPER_STANDARD, STEPPER_FLAT, STEPPER_WITH_CONTROL
	SERIES,
	MODEL,						-- In case of STEPPER_LINEAR, it represents MODEL instead 
	NAME,
	DESCRIPTION, 
	
	FRAME_SIZE,
	FRAME_SIZE_UNIT,			-- mm, cm
	FRAME_SIZE_TYPE,			-- DIAMETER (φ), SIDE (□)
	NEMA_SIZE,
	
	LENGTH,
	LENGTH_UNIT,				-- mm, cm
	
	WEIGHT,
	WEIGHT_UNIT,				-- g
	
	RATED_VOLTAGE,
	RATED_VOLTAGE_UNIT,			-- V
	
	PHASE_CURRENT,
	PHASE_CURRENT_UNIT,			-- A
	
	PHASE_RESISTANCE,
	PHASE_RESISTANCE_UNIT,		-- ohm (Ω)
	
	PHASE_INDUCTANCE,
	PHASE_INDUCTANCE_UNIT,		-- mH
	
	HOLDING_TORQUE,
	HOLDING_TORQUE_UNIT,		-- Nm, Ncm
	
	DETENT_TORQUE,
	DETENT_TORQUE_UNIT,			-- Nm, Ncm
	
	STEP_ANGLE,
	STEP_ANGLE_UNIT,			-- DEG (°)
	
	MAX_THRUST,
	MAX_THRUST_UNIT				-- N
)
VALUES (
	'STEPPER_STANDARD',			-- CATEGORY						-- STEPPER_STANDARD, STEPPER_FLAT, STEPPER_WITH_CONTROL
	@series,					-- SERIES
	@model,						-- MODEL					-- In case of STEPPER_LINEAR, it represents MODEL instead 
	'Standard Stepper Motor',		-- NAME
	NULL,						-- DESCRIPTION 
	
	28,							-- FRAME_SIZE
	'mm',						-- FRAME_SIZE_UNIT			-- mm, cm
	'□',						-- FRAME_SIZE_TYPE			-- DIAMETER (φ), SIDE (□)
	11,							-- NEMA_SIZE
	
	50.5,						-- LENGTH
	'mm',						-- LENGTH_UNIT				-- mm, cm
	
	210,							-- WEIGHT
	'g',						-- WEIGHT_UNIT				-- g
	
	NULL,						-- RATED_VOLTAGE
	NULL,						-- RATED_VOLTAGE_UNIT		-- V
	
	0.67,							-- PHASE_CURRENT
	'A',						-- PHASE_CURRENT_UNIT		-- A
	
	9.2,						-- PHASE_RESISTANCE
	'Ω',						-- PHASE_RESISTANCE_UNIT	-- ohm (Ω)
	
	5.7,						-- PHASE_INDUCTANCE
	'mH',						-- PHASE_INDUCTANCE_UNIT	-- mH
	
	12,						-- HOLDING_TORQUE
	'Ncm',						-- HOLDING_TORQUE_UNIT		-- Nm, Ncm
	
	1.5,						-- DETENT_TORQUE
	'Ncm',						-- DETENT_TORQUE_UNIT		-- Nm, Ncm
	
	1.8,						-- STEP_ANGLE
	'°',						-- STEP_ANGLE_UNIT			-- DEG (°)
	
	NULL,						-- MAX_THRUST
	NULL						-- MAX_THRUST_UNIT			-- N
);


INSERT INTO STEPPER_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'No. of Wires', NULL, '4' FROM STEPPER_MOTOR WHERE MODEL = @model
;

INSERT INTO STEPPER_MOTOR_SPEC (MOTOR_ID, NAME, UNIT, VALUE)
SELECT ID, 'Rotor Inertia', 'g.cm²', '18' FROM STEPPER_MOTOR WHERE MODEL = @model
;

INSERT INTO STEPPER_MOTOR_PERF_MEASUREMENT (MOTOR_ID, TITLE, VARIABLES, CONDITIONS, `VALUES`)
SELECT ID, CONCAT(@model, ' Torque-Frequency Curve'), 'Frequency(Hz), Torque(Ncm)', '24V 0.67A',
'50,7.7
100,7.8
200,8.3
300,8.6
400,9
500,9.3
600,9.5
700,9.5
800,9.5
900,9.5
1000,9.5
1100,9.5
1200,9.5
1300,9.4
1400,9.3
1500,9.1
1600,8.9
1700,8.7
1800,8.6
1900,8.4
2000,8.1
2100,7.5
2200,7
2300,6.5
2400,5.8
2500,4
'
FROM STEPPER_MOTOR WHERE MODEL = @model;

